using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Windows.Forms;
using RiftReference;

// Adversarial cases found during the post-0.12.20 review. Isolated test output only.
class AuditRegressionTests {
 static readonly BindingFlags Hidden=BindingFlags.Instance|BindingFlags.NonPublic;
 static int passed,failed;
 static void Check(bool value,string message){if(!value)throw new Exception(message);}
 static void Test(string name,Action run){try{run();passed++;Console.WriteLine("PASS "+name);}catch(Exception ex){failed++;Console.WriteLine("FAIL "+name+": "+ex.GetBaseException().Message);}}
 static IEnumerable<T> Desc<T>(Control control) where T:Control {foreach(Control child in control.Controls){if(child is T)yield return (T)child;foreach(var nested in Desc<T>(child))yield return nested;}}
 static object Get(Dashboard form,string name){return typeof(Dashboard).GetField(name,Hidden).GetValue(form);}
 static void Call(Dashboard form,string name,params object[] args){typeof(Dashboard).GetMethod(name,Hidden).Invoke(form,args);Application.DoEvents();}
 static void State(Dashboard form,Snapshot value){typeof(Dashboard).GetField("state",Hidden).SetValue(form,value);Call(form,"RefreshPageContext");}
 static HomeProfile Profile(int count){var p=new HomeProfile{Name="QA#local"};for(int i=0;i<count;i++)p.Matches.Add(new HomeMatch{Champion="Vayne",Queue=420,Role="ADC",Result="Victory",Played=new DateTime(2026,9,8,12,0,0,DateTimeKind.Utc).AddHours(-i)});return p;}
 [STAThread] static int Main(){Application.EnableVisualStyles();string root=AppDomain.CurrentDomain.BaseDirectory;
  string prefs=Path.Combine(root,"preferences.json");
  Test("Corrupt preferences survive startup",()=>{File.WriteAllText(prefs,"{interrupted-save");using(var form=new Dashboard(root,true))Check(File.ReadAllText(prefs)=="{interrupted-save","Startup overwrote unreadable preferences");});
  File.WriteAllText(prefs,"{\"SettingsVersion\":2,\"SecondMonitor\":false}");
  Test("Preference writes are atomic and preserve a recovery copy",()=>{PreferencesStore.Save(root,new Preferences{SettingsVersion=2,SecondMonitor=false,AudioVolume=37});Check(PreferencesStore.Read(root).AudioVolume==37,"Saved preference lost");Check(File.Exists(prefs+".bak"),"No recovery copy");string saved=File.ReadAllText(prefs),backup=File.ReadAllText(prefs+".bak");File.WriteAllText(prefs,"null");bool refused=false;try{PreferencesStore.Save(root,new Preferences());}catch{refused=true;}Check(refused&&File.ReadAllText(prefs)=="null"&&File.ReadAllText(prefs+".bak")==backup,"Unreadable settings or recovery copy overwritten");File.WriteAllText(prefs,saved);Check(Directory.GetFiles(root,"preferences.json.*.tmp").Length==0,"Temporary preference file leaked");});
  using(var form=new Dashboard(root,true)){
   form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-30000,-30000);form.Size=new Size(1920,1040);form.Show();State(form,new Snapshot{Account="QA#local",Phase="Lobby",Home=Profile(1)});
   Test("Champion summary refreshes with account history",()=>{Call(form,"NavigatePage","champion:Vayne",true);State(form,new Snapshot{Account="QA#local",Phase="Lobby",Home=Profile(3)});Check(Desc<Label>(form).Any(l=>l.Visible&&l.Text.StartsWith("3 loaded matches")),"Cached champion summary still shows old match count");});
   Test("Reopening a match reuses its page",()=>{int before=Desc<MatchDetailPage>(form).Count();for(int i=0;i<12;i++){Call(form,"NavigatePage","overview",true);var b=(Rectangle)typeof(Dashboard).GetProperty("HomeBounds",Hidden).GetValue(form,null);var row=HomeDashboard.RowBounds(b,0);Call(form,"OnMouseClick",new MouseEventArgs(MouseButtons.Left,1,row.X+20,row.Y+95,0));}Check(Desc<MatchDetailPage>(form).Count()==before+1,"Each click allocates another permanent detail page");});
   Test("New reflections use the current champion and focus",()=>{State(form,new Snapshot{Account="QA#local",Phase="EndOfGame",Players=new List<Player>{new Player{Self=true,Champion="Vayne"}}});Call(form,"NavigatePage","review",true);var page=Desc<ReviewPage>(form).Single();var answer=Desc<TextBox>(page).Single(b=>b.Name=="ReviewAnswer0");answer.Text="Keep this older draft.";((Preferences)Get(form,"prefs")).TrainingFocus="Support position";State(form,new Snapshot{Account="QA#local",Phase="EndOfGame",Players=new List<Player>{new Player{Self=true,Champion="Ashe"}}});Check(answer.Text=="Keep this older draft.","Context refresh replaced draft");Desc<Button>(page).Single(b=>b.Text=="New reflection").PerformClick();Desc<Button>(page).Single(b=>b.Text=="Discard edits").PerformClick();answer.Text="New Ashe reflection";Check(page.Save(),"Could not save reflection");Check(ReflectionStore.Read(root).Last().Champion=="Ashe","New reflection retained first page's champion");});
   Test("Disconnect clears the last account's match context",()=>{typeof(Dashboard).GetField("lastGame",Hidden).SetValue(form,new Snapshot{Account="QA#local",Phase="In game",Players=new List<Player>{new Player{Self=true,Champion="Vayne"}}});State(form,new Snapshot());Check(Get(form,"lastGame")==null,"Last game's lineup survives disconnect");});
   Test("Repaints reuse the backing bitmap",()=>{Call(form,"NavigatePage","overview",true);using(var bitmap=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bitmap,new Rectangle(Point.Empty,form.Size));var first=Get(form,"contentCanvas");for(int i=0;i<8;i++)form.DrawToBitmap(bitmap,new Rectangle(Point.Empty,form.Size));Check(first!=null&&ReferenceEquals(first,Get(form,"contentCanvas")),"Each paint allocates a new full-window bitmap");form.Width=1280;form.DrawToBitmap(bitmap,new Rectangle(Point.Empty,form.Size));Check(!ReferenceEquals(first,Get(form,"contentCanvas")),"Canvas did not follow a resize");}});
   Test("Loading a match blocks review and updates",()=>{State(form,new Snapshot{Phase="GameStart"});Check(!(bool)typeof(Dashboard).GetMethod("CanReview",Hidden).Invoke(form,null)&&!(bool)typeof(Dashboard).GetMethod("CanUpdate",Hidden).Invoke(form,null),"GameStart left destructive actions enabled");State(form,new Snapshot());});
   form.Close();
  }
  Test("Disposed League client cannot restart transport",()=>{var client=new LeagueClient(new DataStore(Path.Combine(root,"data")));client.Dispose();try{client.Clock().GetAwaiter().GetResult();}catch{}var child=typeof(LeagueClient).GetField("transport",Hidden).GetValue(client);client.Dispose();Check(child==null,"A helper was started after disposal");});
  Test("Rank art is cached without locking the source",()=>{using(var icons=new LoadoutIcons(new DataStore(Path.Combine(root,"data")))){var first=icons.GetRankBadge("EMERALD");Check(first!=null,"Missing test rank art");using(var locked=new FileStream(Path.Combine(root,"data","rank-badges","emerald.png"),FileMode.Open,FileAccess.ReadWrite,FileShare.None))Check(ReferenceEquals(first,icons.GetRankBadge("emerald")),"Rank artwork reloaded on every request");}});
  Test("Unchanged scrollbar ranges do not request more painting",()=>{using(var scroll=new HistoryScrollBar()){scroll.CreateControl();int invalidations=0;scroll.Invalidated+=(s,e)=>invalidations++;scroll.Maximum=99;scroll.LargeChange=4;invalidations=0;for(int i=0;i<100;i++){scroll.Maximum=99;scroll.LargeChange=4;}Check(invalidations==0,"Repeated layout invalidated an unchanged scrollbar");}});
  Test("Navigation history is bounded and preserves recent back/forward",()=>{var history=new PageHistory();for(int i=0;i<1000;i++)history.Navigate("detail:"+i);int count=1;while(history.CanBack){history.Back();count++;}Check(count==64&&history.CanForward,"History retained unbounded entries");Check(history.Forward()=="detail:937","Recent navigation order changed");});
  Test("Disposed mobile service cannot restart",()=>{var service=new MobileCompanion(root);service.Dispose();bool rejected=false;try{service.Start("192.168.1.1").GetAwaiter().GetResult();}catch(ObjectDisposedException){rejected=true;}Check(rejected&&!service.Running,"Mobile service restarted after disposal");});
  Test("Recommendation samples reject non-finite counts",()=>{bool rejected=false;try{Recommendations.ValidateChoice(new Dictionary<string,object>{{"games",Double.PositiveInfinity},{"wins",10},{"players",30}});}catch(IOException){rejected=true;}Check(rejected,"Infinite sample count accepted");});
  Test("Matchup context refreshes when the local player becomes known",()=>{using(var page=new LessonsPage(new DataStore(Path.Combine(root,"data")))){page.Size=new Size(1280,950);var state=new Snapshot{Phase="In game",Mode="CLASSIC",Players=new List<Player>{new Player{Champion="Vayne",Role="BOTTOM",Team="ORDER"},new Player{Champion="Lulu",Role="UTILITY",Team="ORDER"},new Player{Champion="Caitlyn",Role="BOTTOM",Team="CHAOS"},new Player{Champion="Nautilus",Role="UTILITY",Team="CHAOS"}}};page.UpdateContext(state);state.Players[0].Self=true;page.UpdateContext(state);Check(Desc<TextBox>(page).Single().Text.Contains("Vayne + Lulu vs Caitlyn + Nautilus"),"Unchanged roster hid a self-identity update");}});
  Console.WriteLine(passed+" audit regressions passed; "+failed+" failed");return failed==0?0:1;
 }
}
