using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Drawing;
using System.Reflection;
using System.Windows.Forms;
using System.Web.Script.Serialization;
using RiftReference;
class OverlayTests {
 static int checks;static void Check(bool ok,string name){if(!ok)throw new Exception(name);checks++;}
 static object Json(object raw){return J.Parse(new JavaScriptSerializer().Serialize(raw));}
 static Dictionary<string,object> Map(object raw){return (Dictionary<string,object>)raw;}
 static object Player(string name,string team,string role,int[] ids){return new{riotId=name+"#TAG",summonerName=name,championName=name=="Self"?"Vayne":"Caitlyn",team=team,position=role,items=ids.Select(id=>new{itemID=id,count=1}).ToArray()};}
 static object Root(object[] events){return Json(new{activePlayer=new{riotId="Self#TAG",currentGold=500},gameData=new{mapNumber=11,gameVersion="16.17.1"},allPlayers=new[]{Player("Self","ORDER","BOTTOM",new[]{1036,1036}),Player("Enemy","CHAOS","BOTTOM",new[]{1036})},events=new{Events=events}});}
 static Snapshot State(double time){return new Snapshot{Phase="In game",Mode="CLASSIC",Time=time};}
 static object Kill(string name,double time,string type,string killer){return new{EventName=name,EventTime=time,DragonType=type,KillerName=killer};}
 [STAThread]static int Main(){try{
  Application.EnableVisualStyles();string home=AppDomain.CurrentDomain.BaseDirectory;var d=new DataStore(Path.Combine(home,"data"));
  var teammates=Enumerable.Range(0,5).Select(i=>Json(new{riotId="Test"+i,team="ORDER",scores=new{kills=2,assists=3,deaths=1,creepScore=150,wardScore=12}})).ToArray();var metrics=LiveOverlayStats.Parse(teammates[0],teammates,1200);Check(metrics.CsPerMinute==7.5&&metrics.KillParticipation==50&&metrics.Vision==12,"Live stats calculations");Check(LiveOverlayStats.Parse(teammates[0],teammates,0).CsPerMinute==null,"Zero clock divided");Check(LiveOverlayStats.Parse(teammates[0],teammates.Take(4).ToArray(),1200).KillParticipation==null,"Partial team KP guessed");foreach(var t in teammates)Map(J.Get(t,"scores"))["kills"]=0;Check(LiveOverlayStats.Parse(teammates[0],teammates,1200).KillParticipation==null,"Zero team kills divided");Map(J.Get(teammates[0],"scores")).Remove("creepScore");Check(LiveOverlayStats.Parse(teammates[0],teammates,1200).CsPerMinute==null,"Missing CS guessed");Check(StatsPanel.Rows(metrics,new OverlayOptions()).Count==2,"Default metrics not compact");Check(StatsPanel.Rows(metrics,new OverlayOptions{StatsCs=true,StatsKda=true,StatsVision=true}).Count==5,"Optional metrics missing");
  using(var form=new PanelLayoutEditor(d,new OverlayOptions{Stats=true,StatsCs=true,StatsKda=true,StatsVision=true})){form.Bounds=new Rectangle(-30000,-30000,1920,1080);form.Show();using(var bmp=new Bitmap(1920,1080)){form.DrawToBitmap(bmp,new Rectangle(0,0,1920,1080));bmp.Save(Path.Combine(home,"overlay-stats.png"));}var widget=form.Controls.OfType<DraggableOverlayPanel>().Single(p=>p.Caption=="YOUR STATS");((Button)widget.Controls.Find("Close panel",false)[0]).PerformClick();Check(!form.Result.Stats&&form.Result.Purchase&&form.Result.Buffs,"Closing stats affected other panels");form.Close();}
  var viewport=new Rectangle(0,0,1920,1080);var defaults=new OverlayOptions();Check(PanelPositions.Build(viewport,new Size(430,202),defaults)==new Point(1186,854),"Build default isn't beside minimap");Check(PanelPositions.Buffs(viewport,new Size(300,124),defaults)==new Point(810,24),"Buff default isn't top center");
  foreach(bool accept in new[]{false,true})using(var form=new PanelLayoutEditor(d,new OverlayOptions{Purchase=false,Buffs=false,Stats=false})){form.Bounds=new Rectangle(-30000,-30000,1920,1080);form.Show();object[] keyArgs={new Message(),accept?Keys.Control|Keys.Enter:Keys.Escape};typeof(PanelLayoutEditor).GetMethod("ProcessCmdKey",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(form,keyArgs);Check(form.DialogResult==(accept?DialogResult.OK:DialogResult.Cancel),"Hidden panels prevented layout accept/cancel");}
  var cardState=CompactOverlayVisuals.Demo();Check(BuffCards.Active(cardState).Count==2&&BuffCards.Size(cardState)==new Size(408,106),"Active card pair size incorrect");cardState.Time=1904;Check(BuffCards.Active(cardState).Count==1&&BuffCards.Active(cardState)[0].Name=="Elder","Expired card remains");cardState.Time=1946;Check(BuffCards.Active(cardState).Count==0,"Cards visible after expiration");
  using(var form=new PanelLayoutEditor(d,new OverlayOptions{BuffsWidth=900,BuffsHeight=500,BuffsPlaced=true,BuffsU=0,BuffsV=1})){form.Bounds=new Rectangle(-30000,-30000,1920,1080);form.Show();var card=form.Controls.OfType<DraggableOverlayPanel>().Single(p=>p.Caption=="BUFF TIMERS · EST.");card.SetLocked(false);Check(card.StaticDisplay&&card.Locked&&card.Size==new Size(408,106)&&card.Location==new Point(756,24),"Buff cards retained old sizing or placement");Check(card.Controls.Cast<Control>().All(c=>!c.Visible),"Buff cards have editor chrome");using(var bmp=new Bitmap(1920,1080)){form.DrawToBitmap(bmp,new Rectangle(Point.Empty,bmp.Size));bmp.Save(Path.Combine(home,"overlay-buff-cards.png"));}form.Close();}
  var oldSize=new OverlayOptions{BuildWidth=600,BuildHeight=280,BuffsWidth=380,BuffsHeight=180,StatsWidth=340,StatsHeight=240};PanelSizing.Migrate(oldSize);PanelSizing.Migrate(oldSize);Check(oldSize.BuildWidth==300&&oldSize.BuildHeight==140&&oldSize.BuffsWidth==190&&oldSize.BuffsHeight==90&&oldSize.StatsWidth==170&&oldSize.StatsHeight==120,"Sizes must halve exactly once");Check(PanelSizing.Fit(new Size(300,124),0,0,viewport.Size)==new Size(150,62)&&PanelSizing.Fit(StatsPanel.Size(defaults),0,0,viewport.Size)==new Size(145,69),"Buff or stats defaults did not halve");Check(PanelTransparency.Clamp(-20)==20&&PanelTransparency.Clamp(150)==100,"Opacity outside visible range");var transparency=new OverlayOptions{PanelSizeVersion=1,BuildOpacity=40,BuffsOpacity=70,StatsOpacity=100};var transparencyCopy=new OverlayOptions();PanelSizing.Copy(new JavaScriptSerializer().Deserialize<OverlayOptions>(new JavaScriptSerializer().Serialize(transparency)),transparencyCopy);Check(transparencyCopy.BuildOpacity==40&&transparencyCopy.BuffsOpacity==70&&transparencyCopy.StatsOpacity==100,"Independent opacity persistence failed");Check(new JavaScriptSerializer().Deserialize<OverlayOptions>("{}").BuildOpacity==96,"Legacy opacity default lost");
  using(var bitmap=new Bitmap(20,20))using(var canvas=Graphics.FromImage(bitmap)){PanelTransparency.Draw(canvas,new Size(20,20),g=>g.Clear(Color.White),50,Color.Black);Check(Math.Abs(bitmap.GetPixel(10,10).R-127)<=2,"Opacity preview not blended");}
  foreach(bool accept in new[]{false,true}){int opacity=96;bool previewed=false;using(var tick=new System.Windows.Forms.Timer{Interval=50}){tick.Tick+=(sender,args)=>{var dialog=Application.OpenForms.Cast<Form>().FirstOrDefault(f=>f.Text=="Panel transparency");if(dialog==null)return;tick.Stop();dialog.Controls.OfType<TrackBar>().Single().Value=55;previewed=opacity==55;using(var bmp=new Bitmap(dialog.Width,dialog.Height)){dialog.DrawToBitmap(bmp,new Rectangle(Point.Empty,dialog.Size));bmp.Save(Path.Combine(home,"overlay-transparency-settings.png"));}dialog.DialogResult=accept?DialogResult.OK:DialogResult.Cancel;dialog.Close();};tick.Start();bool accepted=PanelTransparency.Settings(null,96,value=>opacity=value);Check(previewed&&accepted==accept&&opacity==(accept?55:96),"Opacity dialog preview / accept / cancel failed");}}
  using(var form=new PanelLayoutEditor(d,new OverlayOptions{Stats=true,BuildOpacity=60,BuffsOpacity=80,StatsOpacity=100})){form.Bounds=new Rectangle(-30000,-30000,1920,1080);form.Show();var small=form.Controls.OfType<DraggableOverlayPanel>().Single(p=>p.Caption=="ITEM BUILD");Check(small.Size==new Size(215,101)&&small.PanelOpacity==60,"Compact editor size or opacity mismatch");using(var bmp=new Bitmap(1920,1080)){form.DrawToBitmap(bmp,new Rectangle(0,0,1920,1080));bmp.Save(Path.Combine(home,"overlay-compact-opacity.png"));}form.Close();}
  var moved=new OverlayOptions();PanelPositions.Store(viewport,new Rectangle(400,500,430,202),true,moved);Check(PanelPositions.Build(viewport,new Size(430,202),moved)==new Point(400,500),"Dragged position didn't round-trip");Check(PanelPositions.Buffs(viewport,new Size(300,124),moved)==new Point(810,24),"Build drag moved buffs");var resized=new Rectangle(-1280,0,1280,720);Check(resized.Contains(new Rectangle(PanelPositions.Build(resized,new Size(430,202),moved),new Size(430,202))),"Resized position escaped screen");
  var legacy=new OverlayOptions{X=66,Y=100};PanelPositions.Migrate(legacy);Check(PanelPositions.Build(viewport,new Size(430,202),legacy)==new Point(66,100),"Legacy custom position lost");
  using(var host=new Form{ClientSize=new Size(800,600)})using(var drag=new DraggableOverlayPanel{Size=new Size(200,100),Location=new Point(20,30)}){host.Controls.Add(drag);host.CreateControl();drag.CreateControl();Action<string,int,int> mouse=(method,x,y)=>typeof(DraggableOverlayPanel).GetMethod(method,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(drag,new object[]{new MouseEventArgs(MouseButtons.Left,1,x,y,0)});mouse("OnMouseDown",5,5);mouse("OnMouseMove",70,80);mouse("OnMouseUp",70,80);Check(drag.Location==new Point(20,30),"Locked panel moved");drag.SetLocked(false);mouse("OnMouseDown",40,40);mouse("OnMouseMove",105,115);mouse("OnMouseUp",40,40);Check(drag.Location==new Point(85,105),"Unlocked drag failed");drag.SetLocked(true);mouse("OnMouseDown",5,5);mouse("OnMouseMove",100,100);Check(drag.Location==new Point(85,105),"Relock didn't stop dragging");}
  using(var host=new Form{ClientSize=new Size(800,600)})using(var box=new DraggableOverlayPanel{Bounds=new Rectangle(100,150,300,150)}){host.Controls.Add(box);host.CreateControl();box.CreateControl();Action<string,int,int> mouse=(method,x,y)=>typeof(DraggableOverlayPanel).GetMethod(method,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(box,new object[]{new MouseEventArgs(MouseButtons.Left,1,x,y,0)});mouse("OnMouseDown",299,149);mouse("OnMouseMove",399,199);mouse("OnMouseUp",399,199);Check(box.Size==new Size(300,150),"Locked panel resized");box.SetLocked(false);mouse("OnMouseDown",299,149);mouse("OnMouseMove",399,199);mouse("OnMouseUp",399,199);Check(box.Bounds==new Rectangle(100,150,400,200),"Corner resize failed");mouse("OnMouseDown",0,70);mouse("OnMouseMove",50,70);mouse("OnMouseUp",0,70);Check(box.Bounds==new Rectangle(150,150,350,200),"Left edge did not preserve right edge");mouse("OnMouseDown",349,199);mouse("OnMouseMove",-500,-500);mouse("OnMouseUp",0,0);Check(box.Size==new Size(120,40),"Minimum resize bounds failed");mouse("OnMouseDown",119,39);mouse("OnMouseMove",2000,2000);mouse("OnMouseUp",0,0);Check(host.ClientRectangle.Contains(box.Bounds),"Resize escaped viewport");box.SetLocked(true);var before=box.Bounds;mouse("OnMouseDown",0,0);mouse("OnMouseMove",50,50);mouse("OnMouseUp",50,50);Check(box.Bounds==before,"Relocked resize changed bounds");}
  var sizes=new OverlayOptions{PanelSizeVersion=1,BuildWidth=600,BuildHeight=280,BuffsWidth=380,BuffsHeight=180,StatsWidth=340,StatsHeight=240,Stats=true};var roundTrip=new JavaScriptSerializer().Deserialize<OverlayOptions>(new JavaScriptSerializer().Serialize(sizes));var copied=new OverlayOptions();PanelSizing.Copy(roundTrip,copied);Check(copied.BuildWidth==600&&copied.BuildHeight==280&&copied.BuffsWidth==380&&copied.BuffsHeight==180&&copied.StatsWidth==340&&copied.StatsHeight==240,"Independent dimensions lost");Check(PanelSizing.Fit(new Size(430,202),99999,99999,new Size(800,600))==new Size(800,600),"Saved size not clamped");Check(PanelSizing.Fit(new Size(430,202),0,0,new Size(1920,1080))==new Size(215,101),"Compact size default changed");
  using(var form=new PanelLayoutEditor(d,sizes)){form.Bounds=new Rectangle(-30000,-30000,1920,1080);form.Show();var widget=form.Controls.OfType<DraggableOverlayPanel>().Single(p=>p.Caption=="ITEM BUILD");Check(widget.Size==new Size(600,280),"Saved editor size not restored");widget.SetLocked(false);using(var bmp=new Bitmap(1920,1080)){form.DrawToBitmap(bmp,new Rectangle(0,0,1920,1080));bmp.Save(Path.Combine(home,"overlay-resize.png"));}form.Close();}
  var root=Root(new object[0]);var s=OverlayData.Parse(d,root,State(100));Check(s.Gold==500&&s.Inventory.Count==2,"Active gold / duplicate items lost");Check(s.SelfValue-s.EnemyValue==J.N(J.Get(d.Items["1036"],"gold"),"total"),"Lane diff isn't inventory value");Check(s.Opponent=="Caitlyn","Wrong opponent");
  Check(s.AllyTotal==null&&s.EnemyTotal==null,"Incomplete teams shown as totals");
  var practice=State(100);practice.Mode="PRACTICETOOL";practice.Overlay=OverlayData.Parse(d,root,practice);
  Check(practice.Overlay.Gold==500&&practice.Overlay.InventoryKnown,"Practice Tool inventory not parsed");
  var practiceNow=DateTime.UtcNow;Check(OverlayData.Fresh(practice,practiceNow,practiceNow),"Practice Tool overlay hidden");
  Check(!OverlayData.Fresh(practice,practiceNow,practiceNow.AddSeconds(-5)),"Stale Practice Tool overlay visible");
  practice.Mode="ARAM";Check(!OverlayData.Fresh(practice,practiceNow,practiceNow),"Unsupported mode admitted");
  var ten=new List<object>();for(int i=0;i<5;i++){ten.Add(Player("Ally"+i,"ORDER",ScoreboardData.Roles[i],new[]{1036,1036}));ten.Add(Player("Foe"+i,"CHAOS",ScoreboardData.Roles[i],new[]{1036}));}var tenRaw=J.A(Json(ten.ToArray()));var table=new OverlaySnapshot();ScoreboardData.Populate(d,tenRaw,"ORDER",table);double sword=J.N(J.Get(d.Items["1036"],"gold"),"total");Check(table.AllyTotal==10*sword&&table.EnemyTotal==5*sword,"Team totals wrong");Check(table.Pairs.Count==5&&table.Pairs.All(p=>p.AllyValue-p.EnemyValue==sword),"Five lane rows wrong");Check(ScoreboardData.Difference(table.Pairs[0],false)==-sword,"Flipped arrow semantics wrong");Map(tenRaw[0])["items"]=Json(new[]{new{itemID=999999,count=1}});table=new OverlaySnapshot();ScoreboardData.Populate(d,tenRaw,"ORDER",table);Check(table.AllyTotal==null&&table.EnemyTotal.HasValue,"Unknown item created partial team total");
  foreach(var size in new[]{new Size(1280,720),new Size(1920,1080),new Size(2560,1440)}){var game=new Rectangle(-1920,30,size.Width,size.Height);foreach(int scale in new[]{60,100,160}){var alignment=new OverlayOptions{BoardScale=scale,BoardX=1000,BoardY=900,RowStart=300,RowGap=140};Check(game.Contains(ScoreboardLayout.Bounds(game,alignment)),"Alignment escaped game viewport");}}
  var oldSettings=new JavaScriptSerializer().Deserialize<OverlayOptions>("{\"Enabled\":true,\"Target\":3031}");Check(oldSettings.RowGap==88&&oldSettings.BoardScale==100&&oldSettings.AlliesLeft,"Old overlay settings failed defaults migration");
  var roster=J.A(J.Get(root,"allPlayers"));Map(roster[1])["position"]="UTILITY";Check(OverlayData.Parse(d,root,State(100)).EnemyValue==null,"Support paired as ADC");Map(roster[1])["position"]="BOTTOM";Map(root)["allPlayers"]=new[]{roster[0],roster[1],roster[1]};Check(OverlayData.Parse(d,root,State(100)).EnemyValue==null,"Ambiguous opponent guessed");
  root=Root(new object[0]);Map(J.Get(root,"activePlayer")).Remove("currentGold");Check(OverlayData.Parse(d,root,State(100)).Gold==null,"Missing gold treated as zero");Map(J.Get(root,"activePlayer"))["currentGold"]=0;Check(OverlayData.Parse(d,root,State(100)).Gold==0,"Real zero missing");
  Map(J.A(J.Get(root,"allPlayers"))[0]).Remove("items");Check(!OverlayData.Parse(d,root,State(100)).InventoryKnown,"Missing inventory treated as empty");Check(OverlayData.Value(d,new List<int>{999999})==null,"Unknown price silently omitted");Check(OverlayData.Inventory(Json(new{items=new[]{new{itemID=1036,count=2}}})).Count==2,"Stack count lost");Check(OverlayData.Inventory(Json(new{items=new[]{new{itemID=1036}}}))==null,"Missing count accepted");
  root=Root(new[]{Kill("BaronKill",100,"","Self"),Kill("DragonKill",110,"Elder","Enemy#TAG"),Kill("DragonKill",115,"Fire","Self")});s=OverlayData.Parse(d,root,State(120));Check(s.Buffs.Count==2&&s.Buffs[0].Team=="Allies"&&s.Buffs[1].Team=="Enemies","Objective identity mapping");Check(s.Buffs[0].Ends==280&&s.Buffs[1].Ends==260,"Wrong buff expiration");Check(OverlayData.Parse(d,root,State(260)).Buffs.Count==1,"Expired Elder retained");Check(OverlayData.Parse(d,root,State(280)).Buffs.Count==0,"Expired Baron retained");Check(OverlayData.Parse(d,root,State(99)).Buffs.Count==0,"Future events accepted");Check(OverlayData.Parse(d,Root(new object[0]),State(5)).Buffs.Count==0,"New game retained events");
  Check(OverlayData.Parse(d,Root(new[]{Kill("BaronKill",100,"","unknown")}),State(120)).Buffs[0].Team=="Team unknown","Unknown killer assigned a team");var post=State(120);post.Phase="EndOfGame";Check(OverlayData.Parse(d,root,post).Buffs.Count==0,"Postgame overlay populated");
  // Use a small independent recipe: final 1800 = intermediate 1000 + two swords 300 + combine 200.
  var actual=d.Items;d.Items=new Dictionary<string,object>{{"1",Json(new{gold=new{total=300},name="Sword"})},{"2",Json(new{gold=new{total=1000},from=new[]{"1","1"},name="Twin blade"})},{"3",Json(new{gold=new{total=1800},from=new[]{"2","1","1"},name="Final"})}};
  Check(OverlayData.Cost(d,3,new List<int>()).Remaining==1800,"Empty inventory price");Check(OverlayData.Cost(d,3,new List<int>{1}).Remaining==1500,"Single component counted twice");Check(OverlayData.Cost(d,3,new List<int>{1,1,1}).Remaining==900,"Duplicate requirements mishandled");Check(OverlayData.Cost(d,3,new List<int>{2,1,1}).Remaining==200,"Combine cost incorrect");Check(OverlayData.Cost(d,3,new List<int>{3}).Owned&&OverlayData.Cost(d,3,new List<int>{3}).Remaining==0,"Already owned ignored");Check(OverlayData.Cost(d,3,new List<int>{99}).Remaining==1800,"Unrelated item reduced price");
  d.Items["1"]=Json(new{gold=new{total=300},from=new[]{"3"}});bool rejected=false;try{OverlayData.Cost(d,3,new List<int>());}catch(ArgumentException){rejected=true;}Check(rejected,"Cyclic recipe accepted");d.Items=actual;
  var now=DateTime.UtcNow;var state=State(120);state.Overlay=s;Check(OverlayData.Fresh(state,now,now.AddSeconds(-3)),"Fresh data hidden");Check(!OverlayData.Fresh(state,now,now.AddSeconds(-5)),"Stale data shown");state.Demo=true;Check(!OverlayData.Fresh(state,now,now),"Demo leaks over game");state.Demo=false;state.Phase="Waiting";Check(!OverlayData.Fresh(state,now,now),"Lobby overlay visible");
  string champ,patch;var plan=new{format="rift-loadout-1",champion="Vayne",patch=d.Version,sections=new[]{new{name="Core",items="1036, 3031"}}};Check(OverlaySettings.PlanItems(d,new JavaScriptSerializer().Serialize(plan),out champ,out patch).SequenceEqual(new[]{1036,3031})&&champ=="Vayne","Saved plan target load failed");
  var opt=new OverlayOptions{Enabled=true,Gold=false,Buffs=true,Purchase=false,Target=3031,Champion="Vayne",X=66,Y=100,Key=9};OverlayStorage.Save(home,opt);OverlayStorage.Save(home,opt);var saved=new JavaScriptSerializer().Deserialize<OverlayOptions>(File.ReadAllText(Path.Combine(home,"overlay.json")));Check(saved.Enabled&&!saved.Gold&&!saved.Purchase&&saved.Buffs&&saved.X==66&&saved.Champion=="Vayne","Settings persistence lost");Check(File.Exists(Path.Combine(home,"overlay.json.bak")),"Settings recovery missing");Check(!new OverlayOptions().Enabled,"Overlay default on");
  using(var window=new OverlayWindow()){var cp=(CreateParams)typeof(OverlayWindow).GetProperty("CreateParams",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(window,null);Check((cp.ExStyle&0x08080020)==0x08080020&&!window.ShowInTaskbar,"Overlay activation / clickthrough flags");}
  GameOverlay.Preview(d,Path.Combine(home,"overlay-preview.png"));using(var form=new OverlaySettings(d,opt)){form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-30000,-30000);form.Show();using(var bmp=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bmp,new Rectangle(Point.Empty,form.Size));bmp.Save(Path.Combine(home,"overlay-settings.png"));}form.Close();}
  bool statsToggles=false;using(var tick=new Timer{Interval=50}){tick.Tick+=(sender,args)=>{var dialog=Application.OpenForms.Cast<Form>().FirstOrDefault(f=>f.Text=="Stats panel settings");if(dialog==null)return;tick.Stop();statsToggles=dialog.Controls.OfType<CheckBox>().Any()&&dialog.Controls.OfType<CheckBox>().All(c=>c is RiftToggle);using(var bmp=new Bitmap(dialog.Width,dialog.Height)){dialog.DrawToBitmap(bmp,new Rectangle(Point.Empty,dialog.Size));bmp.Save(Path.Combine(home,"overlay-stats-settings.png"));}dialog.DialogResult=DialogResult.Cancel;dialog.Close();};tick.Start();Check(!StatsPanel.Settings(null,new OverlayOptions())&&statsToggles,"Stats settings retained native checkboxes");}
  using(var form=new ScoreboardAlignment(d,opt)){form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-30000,-30000);form.Show();Check(form.Controls.OfType<CheckBox>().All(c=>c is RiftToggle),"Scoreboard alignment retained a native checkbox");using(var bmp=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bmp,new Rectangle(Point.Empty,form.Size));bmp.Save(Path.Combine(home,"overlay-alignment.png"));}form.Close();}
  using(var form=new PanelLayoutEditor(d,new OverlayOptions())){form.Bounds=new Rectangle(-30000,-30000,1920,1080);form.Show();using(var bmp=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bmp,new Rectangle(Point.Empty,form.Size));bmp.Save(Path.Combine(home,"overlay-move-panels.png"));}form.Close();}
  using(var form=new PanelLayoutEditor(d,new OverlayOptions())){form.Bounds=new Rectangle(-30000,-30000,1920,1080);form.Show();var panels=form.Controls.OfType<DraggableOverlayPanel>().ToArray();var first=panels.First(p=>p.Caption=="ITEM BUILD");var second=panels.First(p=>p.Caption=="BUFF TIMERS · EST.");((Button)first.Controls.Find("Lock position",false)[0]).PerformClick();Check(!first.Locked&&second.Locked,"Panel locks are not independent");((Button)first.Controls.Find("Lock position",false)[0]).PerformClick();Check(first.Locked,"Panel lock did not relock");((Button)first.Controls.Find("Close panel",false)[0]).PerformClick();Check(!form.Result.Purchase&&form.Result.Buffs&&second.Visible,"Close disabled both panels");Check(!form.Controls.OfType<Panel>().Any(),"Shared layout toolbar remains");var menu=(ContextMenuStrip)typeof(DraggableOverlayPanel).GetField("menu",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(first);Check(menu.Items.Cast<ToolStripItem>().Any(i=>i.Text=="Use layout · Ctrl+Enter")&&menu.Items.Cast<ToolStripItem>().Any(i=>i.Text=="Reset this panel"),"Panel gear missing relocated actions");form.Close();}
  Console.WriteLine(checks+" overlay checks passed. Live League focus/Tab/click-through and fullscreen behavior still require game validation.");return 0;
 }catch(Exception ex){Console.Error.WriteLine(ex);return 1;}}
}
