using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Windows.Forms;
using RiftReference;
class UxInteractionTests {
 static readonly BindingFlags Hidden=BindingFlags.Instance|BindingFlags.NonPublic;static int checks;
 static void Check(bool ok,string message){if(!ok)throw new Exception(message);checks++;}
 static object Get(object owner,string field){return owner.GetType().GetField(field,Hidden).GetValue(owner);}
 static void Call(object owner,string method,params object[] args){owner.GetType().GetMethod(method,Hidden).Invoke(owner,args);}
 static IEnumerable<Control> Desc(Control parent){foreach(Control child in parent.Controls){yield return child;foreach(var next in Desc(child))yield return next;}}
 static void Capture(Dashboard form,string file){Application.DoEvents();using(var bitmap=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bitmap,new Rectangle(Point.Empty,form.Size));bitmap.Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,file+".png"));}}
 static void Paint(Control control){using(var bitmap=new Bitmap(control.Width,control.Height))using(var g=Graphics.FromImage(bitmap))Call(control,"OnPaint",new PaintEventArgs(g,control.ClientRectangle));}
 [STAThread]static int Main(){try{Application.EnableVisualStyles();string root=AppDomain.CurrentDomain.BaseDirectory;using(var form=new Dashboard(root,true)){
  ((Preferences)Get(form,"prefs")).SecondMonitor=false;form.StartPosition=FormStartPosition.Manual;form.Location=new Point(-30000,-30000);form.Size=new Size(1920,1040);form.Show();var profile=new HomeProfile{Name="SAMPLE DATA · UX QA",Rank="Emerald II",Tier="EMERALD",LP=64,Wins=42,Losses=38};
  for(int i=0;i<100;i++)profile.Matches.Add(new HomeMatch{GameId=i+1,Champion=i%3==0?"Ashe":"Vayne",Role="ADC",Queue=420,Result=i%2==0?"Victory":"Defeat",Played=DateTime.UtcNow.AddHours(-i),Kills=8,Deaths=4,Assists=6,CS=210,Duration=1800,Vision=19,Damage=24000,Items=new int?[]{3153,3006,3124,0,null,0,3363}});
  var snapshot=new Snapshot{Account=profile.Name,Phase="Lobby",Home=profile};typeof(Dashboard).GetField("state",Hidden).SetValue(form,snapshot);Call(form,"RefreshPageContext");Call(form,"NavigatePage","overview",true);Paint(form);var surface=(HomeOverview)Get(form,"homeOverview");Paint(surface);
  var search=(MatchSearch)Get(form,"matchSearch");var queue=(RiftComboBox)Get(form,"historyQueue");var range=(RiftComboBox)Get(form,"historyRange");var scroll=(HistoryScrollBar)Get(form,"historyScroll");
  Check(surface.Visible&&surface.TabStop,"Overview is not keyboard reachable");Check(surface.AccessibilityObject.GetChildCount()==105,"Overview must expose both statistics, all records and its three native controls");Check(surface.AccessibilityObject.GetChild(0).Name.Contains("64 LP"),"Profile statistics inaccessible");Check(surface.AccessibilityObject.GetChild(1).Name.Contains("100 matches"),"Filtered summary inaccessible");var first=surface.AccessibilityObject.GetChild(2);Check(first.Name.Contains("Ashe")&&first.Name.Contains("Kills 8")&&first.Name.Contains("CS 210")&&first.DefaultAction=="Open match details","Match semantics/action incomplete");Check(surface.AccessibilityObject.GetChild(101).Bounds.IsEmpty,"Hidden match claims visible bounds");
  Check(Enumerable.Range(102,3).Select(i=>surface.AccessibilityObject.GetChild(i).Name).OrderBy(x=>x).SequenceEqual(new[]{"Match history","Match queue","Match range"}),"Native filters hidden by custom accessibility provider");Check(queue.Parent==surface&&range.Parent==surface&&scroll.Parent==surface,"History controls must belong to their painted surface");
  first.DoDefaultAction();Check(Desc(form).OfType<MatchDetailPage>().Single().Visible,"Accessible match action did not open details");Call(form,"NavigatePage",((PageHistory)Get(form,"pageHistory")).Back(),false);surface.Focus();Call(surface,"OnKeyDown",new KeyEventArgs(Keys.End));Check(surface.SelectedIndex==99&&scroll.Value==scroll.Limit,"Keyboard End must select and reveal last match");Check((surface.AccessibilityObject.GetFocused().State&AccessibleStates.Focused)!=0,"Focused match absent from accessibility");Capture(form,"ux-overview-focused-last");Call(surface,"OnKeyDown",new KeyEventArgs(Keys.PageUp));Check(surface.SelectedIndex==99-HomeDashboard.VisibleMatches(surface.ClientRectangle),"Page Up skipped wrong number of matches");Call(surface,"OnKeyDown",new KeyEventArgs(Keys.Home));Check(surface.SelectedIndex==0&&scroll.Value==0,"Home did not restore first row");
  Call(surface,"OnKeyDown",new KeyEventArgs(Keys.Down));Call(surface,"OnKeyDown",new KeyEventArgs(Keys.Enter));Check(((PageHistory)Get(form,"pageHistory")).Current.StartsWith("detail:"),"Enter did not open keyboard-selected match");Call(form,"NavigatePage","overview",true);
  int full=(int)Get(surface,"fullRenderCount"),rowPaints=(int)Get(surface,"rowRenderCount"),parentInvalidations=0;form.Invalidated+=(s,e)=>parentInvalidations++;scroll.Value=20;Paint(surface);Check((int)Get(surface,"fullRenderCount")==full&&(int)Get(surface,"rowRenderCount")==rowPaints+1,"Scrolling repainted static profile or did not render rows");Check(parentInvalidations==0,"Scrollbar invalidated whole window");Paint(surface);Check((int)Get(surface,"rowRenderCount")==rowPaints+1,"Unchanged paint rebuilt table");
  var wheel=new HandledMouseEventArgs(MouseButtons.None,0,20,20,-120);Call(surface,"OnMouseWheel",wheel);Check(wheel.Handled&&scroll.Value==21,"Overview wheel must scroll once and stop bubbling");wheel=new HandledMouseEventArgs(MouseButtons.None,0,5,5,-120);Call(scroll,"OnMouseWheel",wheel);Check(wheel.Handled&&scroll.Value==22,"Scrollbar wheel must stop bubbling to overview");
  var shell=Get(form,"shellCanvas");var main=Get(form,"contentCanvas");for(int i=0;i<10;i++){form.Location=new Point(-30000+i,-30000);Paint(form);}Check(ReferenceEquals(shell,Get(form,"shellCanvas"))&&ReferenceEquals(main,Get(form,"contentCanvas")),"Moving rebuilt frame buffers");
  search.Text="No matching champion";Check(surface.MatchCount==0&&!scroll.Visible&&queue.Visible,"Empty filter retained stale rows");Check(surface.AccessibilityObject.GetChild(1).Name.Contains("0 matches"),"Empty summary stale");Capture(form,"ux-overview-empty-filter");search.Text="Ashe";Check(surface.MatchCount==34&&scroll.Value==0,"Search did not refresh/reset history");Capture(form,"ux-overview-filtered");
  foreach(string route in new[]{"champions","rank","matchups","review","match"}){Call(form,"NavigatePage",route,true);Check(!search.Visible&&!surface.Visible,"Overview search/surface leaked onto "+route);Check(((Panel)Get(form,"pageTrail")).Visible&&((Button)Get(form,"backPage")).Visible,"History arrows missing from "+route);Capture(form,"ux-"+route);}
  Call(form,"NavigatePage","overview",true);Check(search.Visible&&search.Text=="Ashe"&&surface.MatchCount==34,"Returning lost overview filters");
  Call(form,"NavigatePage","champions",true);var champions=Desc(form).OfType<ChampionsPage>().Single();var your=Desc(champions).OfType<Button>().Single(b=>b.Text=="Your champions");var catalog=Desc(champions).OfType<Button>().Single(b=>b.Text=="Champion catalog");Check(your.BackColor==Theme.Accent&&catalog.BackColor!=Theme.Accent,"Active champion section unmarked");catalog.PerformClick();Check(catalog.BackColor==Theme.Accent&&your.BackColor!=Theme.Accent,"Catalog active state missing");Check(Desc(champions).OfType<ChampionHistoryButton>().First().Text=="Vayne","Catalog silently ignored Most played sort");Capture(form,"ux-champion-catalog");
  foreach(int width in new[]{1280,1920}){form.Size=new Size(width,width==1920?1040:950);foreach(bool draft in new[]{true,false}){var state=form.Demo(draft);typeof(Dashboard).GetField("state",Hidden).SetValue(form,state);Call(form,"NavigatePage","match",true);Capture(form,"ux-"+(draft?"draft":"live")+"-"+width);Check(((Panel)Get(form,"pageTrail")).Bottom<70+72,"Live toolbar overlaps heading");}typeof(Dashboard).GetField("state",Hidden).SetValue(form,DashboardFixtures.Results(form.Demo(false)));Capture(form,"ux-postgame-"+width);}
  typeof(Dashboard).GetField("state",Hidden).SetValue(form,new Snapshot());Call(form,"NavigatePage","overview",true);Paint(form);Check(surface.MatchCount==0&&surface.AccessibilityObject.GetChild(0).Name.Contains("unavailable"),"Disconnect retained accessible account data");Capture(form,"ux-disconnected");form.Close();
 }Console.WriteLine(checks+" UX accessibility/navigation/render-cache checks passed");return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
}
