using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Linq;
using System.Windows.Forms;

namespace RiftReference {
public sealed class GoldPair {public string Role,Ally,Enemy;public double? AllyValue,EnemyValue;}
public static class ScoreboardData {
 public static readonly string[] Roles={"TOP","JUNGLE","MIDDLE","BOTTOM","UTILITY"};
 public static void Populate(DataStore data,object[] players,string team,OverlaySnapshot result){
  string other=team=="ORDER"?"CHAOS":"ORDER";var allies=players.Where(p=>J.S(p,"team")==team).ToArray();var enemies=players.Where(p=>J.S(p,"team")==other).ToArray();
  result.AllyTotal=Total(data,allies);result.EnemyTotal=Total(data,enemies);
  foreach(string role in Roles){var a=allies.Where(p=>LaneView.Role(J.S(p,"position"))==role).ToArray();var e=enemies.Where(p=>LaneView.Role(J.S(p,"position"))==role).ToArray();var pair=new GoldPair{Role=role};if(a.Length==1){pair.Ally=data.Name(J.S(a[0],"championName"));pair.AllyValue=OverlayData.Value(data,OverlayData.Inventory(a[0]));}if(e.Length==1){pair.Enemy=data.Name(J.S(e[0],"championName"));pair.EnemyValue=OverlayData.Value(data,OverlayData.Inventory(e[0]));}result.Pairs.Add(pair);}
 }
 static double? Total(DataStore data,object[] team){if(team.Length!=5)return null;var ids=team.Select(p=>J.S(p,"riotId")!=""?J.S(p,"riotId"):J.S(p,"summonerName")).ToArray();if(ids.Any(id=>id=="")||ids.Distinct().Count()!=5)return null;var values=team.Select(p=>OverlayData.Value(data,OverlayData.Inventory(p))).ToArray();return values.All(v=>v.HasValue)?(double?)values.Sum(v=>v.Value):null;}
 public static double? Difference(GoldPair pair,bool alliesLeft){return alliesLeft?pair.AllyValue-pair.EnemyValue:pair.EnemyValue-pair.AllyValue;}
}
public static class ScoreboardLayout {
 public static float Scale(Size game,OverlayOptions opt){float requested=Math.Max(.45f,Math.Min(2.5f,game.Height/1080f*Math.Max(60,Math.Min(160,opt.BoardScale))/100f));return Math.Min(requested,Math.Min(game.Width/440f,game.Height/(float)(Start(opt)+4*Gap(opt)+34)));}
 public static int Start(OverlayOptions opt){return Math.Max(90,Math.Min(300,opt.RowStart));}
 public static int Gap(OverlayOptions opt){return Math.Max(50,Math.Min(140,opt.RowGap));}
 public static Rectangle Bounds(Rectangle game,OverlayOptions opt){float s=Scale(game.Size,opt);int w=(int)Math.Ceiling(440*s),h=(int)Math.Ceiling((Start(opt)+4*Gap(opt)+34)*s);int x=game.Left+game.Width/2+(int)(opt.BoardX*s)-w/2,y=game.Top+(int)(opt.BoardY*s);return new Rectangle(Math.Max(game.Left,Math.Min(x,game.Right-w)),Math.Max(game.Top,Math.Min(y,game.Bottom-h)),w,h);}
}
public sealed class CompactOverlayVisuals:IDisposable {
 readonly DataStore data;readonly LoadoutIcons icons;
 readonly Font small=new Font("Segoe UI",9),label=new Font("Segoe UI",11,FontStyle.Bold),number=new Font("Segoe UI",18,FontStyle.Bold),title=new Font("Segoe UI",14,FontStyle.Bold);
 static readonly Color Blue=Color.FromArgb(95,190,235),Red=Color.FromArgb(240,100,110),Gold=Color.FromArgb(168,146,88),Ready=Color.FromArgb(116,224,147),Surface=Color.FromArgb(19,29,35),Ink=Color.FromArgb(231,239,242),Muted=Color.FromArgb(150,163,171);
 public CompactOverlayVisuals(DataStore d){data=d;icons=new LoadoutIcons(d);}
 public void Configure(Snapshot state,OverlayOptions opt,Size game,OverlayWindow board,OverlayWindow build,OverlayWindow buffs){float scale=ScoreboardLayout.Scale(game,opt);board.ClientSize=ScoreboardLayout.Bounds(new Rectangle(Point.Empty,game),opt).Size;board.Painter=g=>DrawBoard(g,state.Overlay,opt,scale);var buildBase=new Size(430,202);build.ClientSize=PanelSizing.Fit(buildBase,opt.BuildWidth,opt.BuildHeight,game);build.Painter=g=>PanelSizing.Draw(g,build.ClientSize,buildBase,p=>DrawBuild(p,state.Overlay,opt));buffs.ClientSize=BuffCards.Size(state);buffs.Painter=g=>DrawBuffs(g,state);board.Invalidate();build.Invalidate();buffs.Invalidate();}
 void Text(Graphics g,string text,Font font,Color color,RectangleF rect,bool center=false){using(var brush=new SolidBrush(color))using(var format=new StringFormat{Alignment=center?StringAlignment.Center:StringAlignment.Near,LineAlignment=StringAlignment.Center,Trimming=StringTrimming.EllipsisCharacter,FormatFlags=StringFormatFlags.NoWrap})g.DrawString(text,font,brush,rect,format);}
 void Panel(Graphics g,Rectangle rect){using(var b=new SolidBrush(Surface))g.FillRectangle(b,rect);using(var p=new Pen(Gold,1.5f))g.DrawRectangle(p,rect.X+1,rect.Y+1,rect.Width-2,rect.Height-2);}
 static string Amount(double? value){return value.HasValue?value.Value.ToString("0"):"—";}
 void Arrow(Graphics g,float x,float y,bool left,Color color){using(var b=new SolidBrush(color))g.FillPolygon(b,left?new[]{new PointF(x-6,y),new PointF(x+5,y-7),new PointF(x+5,y+7)}:new[]{new PointF(x+6,y),new PointF(x-5,y-7),new PointF(x-5,y+7)});}
 public void DrawBoard(Graphics g,OverlaySnapshot snapshot,OverlayOptions opt,float scale){
  var s=snapshot??new OverlaySnapshot();g.Clear(Color.Magenta);var saved=g.Save();g.ScaleTransform(scale,scale);g.SmoothingMode=SmoothingMode.None;g.TextRenderingHint=TextRenderingHint.AntiAliasGridFit;
  Panel(g,new Rectangle(0,0,440,72));double? left=opt.AlliesLeft?s.AllyTotal:s.EnemyTotal,right=opt.AlliesLeft?s.EnemyTotal:s.AllyTotal;double? diff=left-right;
  Text(g,Amount(left),number,Blue,new RectangleF(20,4,135,33),true);Text(g,Amount(right),number,Red,new RectangleF(285,4,135,33),true);Text(g,diff.HasValue?Math.Abs(diff.Value).ToString("0"):"—",label,diff>0?Blue:diff<0?Red:Muted,new RectangleF(163,4,114,33),true);
  if(diff.HasValue&&diff!=0)Arrow(g,220,43,diff>0,diff>0?Blue:Red);
  Text(g,"ITEM VALUE · ESTIMATE",small,Muted,new RectangleF(90,48,260,18),true);Text(g,opt.AlliesLeft?"ALLIES":"ENEMIES",small,Blue,new RectangleF(20,33,135,18),true);Text(g,opt.AlliesLeft?"ENEMIES":"ALLIES",small,Red,new RectangleF(285,33,135,18),true);
  for(int i=0;i<5;i++){string role=ScoreboardData.Roles[i];var pair=s.Pairs.FirstOrDefault(p=>p.Role==role);double? delta=pair==null?null:ScoreboardData.Difference(pair,opt.AlliesLeft);int y=ScoreboardLayout.Start(opt)+i*ScoreboardLayout.Gap(opt);Panel(g,new Rectangle(180,y-26,80,53));Color color=delta>0?Blue:delta<0?Red:Muted;Text(g,delta.HasValue?Math.Abs(delta.Value).ToString("0"):"—",label,color,new RectangleF(182,y-26,76,23),true);if(delta.HasValue&&delta!=0)Arrow(g,220,y+3,delta>0,color);Text(g,role=="UTILITY"?"SUP":role=="BOTTOM"?"BOT":role=="MIDDLE"?"MID":role=="JUNGLE"?"JG":role,small,Muted,new RectangleF(184,y+10,72,14),true);}
  g.Restore(saved);
 }
 void Icon(Graphics g,int id,Rectangle rect,Color border){var img=icons.Get("items",id);if(img!=null)g.DrawImage(img,rect);else{using(var b=new SolidBrush(Color.FromArgb(42,49,54)))g.FillRectangle(b,rect);Text(g,"?",title,Muted,rect,true);}using(var p=new Pen(border,2))g.DrawRectangle(p,rect);}
 public void DrawBuild(Graphics g,OverlaySnapshot snapshot,OverlayOptions opt){
  var s=snapshot??new OverlaySnapshot();g.Clear(Surface);g.TextRenderingHint=TextRenderingHint.AntiAliasGridFit;Panel(g,new Rectangle(0,0,430,202));Text(g,(s.Champion==""?"Your champion":data.Name(s.Champion))+" · Build",title,Ink,new RectangleF(14,8,400,30));
  object item;if(opt.Target==0||opt.Champion!=s.Champion||!data.Items.TryGetValue(opt.Target.ToString(),out item)){Text(g,"Choose a target in Game overlay settings",label,Ink,new RectangleF(16,57,400,34));Text(g,"Select an item or load your saved build plan.",small,Muted,new RectangleF(16,100,400,28));Text(g,"Manual plan · Probuilds feed not connected",small,Muted,new RectangleF(16,166,400,22));return;}
  var children=J.A(J.Get(item,"from")).Select(v=>Convert.ToInt32(v)).ToArray();var pool=new List<int>(s.Inventory);int visible=Math.Min(3,children.Length);
  for(int i=0;i<visible;i++){int id=children[i];bool owned=s.InventoryKnown&&pool.Remove(id);double? gap=null;try{if(s.InventoryKnown&&s.Gold.HasValue)gap=Math.Max(0,Math.Ceiling(OverlayData.Cost(data,id,s.Inventory).Remaining-s.Gold.Value));}catch(ArgumentException){}int x=16+i*83;Icon(g,id,new Rectangle(x,58,62,62),owned||gap==0?Ready:Gold);Text(g,owned?"Owned":gap==0?"Ready":gap.HasValue?gap.Value.ToString("0")+"g":"—",label,owned||gap==0?Ready:Ink,new RectangleF(x-3,125,70,22),true);}
  if(children.Length==0)Text(g,"Direct purchase",small,Muted,new RectangleF(16,68,238,36),true);
  Text(g,"→",number,Gold,new RectangleF(264,64,35,45),true);Icon(g,opt.Target,new Rectangle(323,53,76,76),Gold);
  string progress="—";Color progressColor=Ink;double fraction=0;try{if(s.InventoryKnown&&s.Gold.HasValue){var cost=OverlayData.Cost(data,opt.Target,s.Inventory);double missing=Math.Max(0,Math.Ceiling(cost.Remaining-s.Gold.Value));progress=cost.Owned?"Owned":missing==0?"Ready":missing.ToString("0")+"g";progressColor=cost.Owned||missing==0?Ready:Ink;fraction=cost.Remaining==0?1:Math.Min(1,s.Gold.Value/cost.Remaining);}}catch(ArgumentException){}
  using(var b=new SolidBrush(Color.FromArgb(46,57,63)))g.FillRectangle(b,321,132,80,23);using(var b=new SolidBrush(Color.FromArgb(45,108,71)))g.FillRectangle(b,321,132,(int)(80*fraction),23);Text(g,progress,label,progressColor,new RectangleF(321,131,80,23),true);
  Text(g,J.S(item,"name"),small,Ink,new RectangleF(16,150,294,20));Text(g,"Gold needed · estimates / manual plan",small,Muted,new RectangleF(16,175,400,18));
 }
 public void DrawBuffs(Graphics g,Snapshot state){BuffCards.Draw(g,state);}
 public void Dispose(){icons.Dispose();small.Dispose();label.Dispose();number.Dispose();title.Dispose();}
 public static Snapshot Demo(){var s=new Snapshot{Phase="In game",Mode="CLASSIC",Time=1800,Demo=true,Overlay=new OverlaySnapshot{Champion="Vayne",Gold=850,InventoryKnown=true,Inventory=new List<int>{1042},AllyTotal=25978,EnemyTotal=24050}};double[] diffs={1383,825,-200,-80,0};for(int i=0;i<5;i++)s.Overlay.Pairs.Add(new GoldPair{Role=ScoreboardData.Roles[i],AllyValue=4810+diffs[i],EnemyValue=4810});s.Overlay.Buffs.Add(new BuffWindow{Name="Baron",Team="Allies",Ends=1904});s.Overlay.Buffs.Add(new BuffWindow{Name="Elder",Team="Enemies",Ends=1946});return s;}
 public static void RenderPreview(DataStore d,string path){using(var visual=new CompactOverlayVisuals(d))using(var bmp=new Bitmap(1920,1080))using(var g=Graphics.FromImage(bmp))using(var font=new Font("Segoe UI",14)){
   g.Clear(Color.FromArgb(15,16,20));g.DrawString("RIFT READY · SCOREBOARD OVERLAY PREVIEW · simulated data",font,Brushes.Gray,28,26);var opt=new OverlayOptions{Target=3153,Champion="Vayne"};var s=Demo();
   // A neutral schematic supplies context; no competitor artwork is shipped.
   using(var bg=new SolidBrush(Color.FromArgb(19,29,35)))g.FillRectangle(bg,340,280,1240,570);using(var line=new Pen(Color.FromArgb(55,65,69)))for(int i=0;i<5;i++){int y=340+i*88;g.DrawRectangle(line,350,y,1220,82);g.DrawString(ScoreboardData.Roles[i]+"   /   ALLY",font,Brushes.Gray,380,y+22);g.DrawString("ENEMY   /   "+ScoreboardData.Roles[i],font,Brushes.Gray,1280,y+22);}
   var board=ScoreboardLayout.Bounds(new Rectangle(0,0,1920,1080),opt);using(var layer=new Bitmap(board.Width,board.Height))using(var lg=Graphics.FromImage(layer)){visual.DrawBoard(lg,s.Overlay,opt,1);layer.MakeTransparent(Color.Magenta);g.DrawImageUnscaled(layer,board.Location);}
   using(var layer=new Bitmap(215,101))using(var lg=Graphics.FromImage(layer)){PanelSizing.Draw(lg,layer.Size,new Size(430,202),p=>visual.DrawBuild(p,s.Overlay,opt));g.DrawImageUnscaled(layer,PanelPositions.Build(new Rectangle(0,0,1920,1080),layer.Size,opt));}using(var layer=new Bitmap(BuffCards.Size(s).Width,BuffCards.Size(s).Height))using(var lg=Graphics.FromImage(layer)){visual.DrawBuffs(lg,s);g.DrawImageUnscaled(layer,PanelPositions.Buffs(new Rectangle(0,0,1920,1080),layer.Size,opt));}bmp.Save(path);
  }}
}
public static class BuffCards {
 public static List<BuffWindow> Active(Snapshot s){return s.Overlay.Buffs.Where(b=>(b.Name=="Baron"||b.Name=="Elder")&&b.Ends>s.Time&&b.Ends-s.Time<=BuffWindow.Duration(b.Name)).OrderBy(b=>b.Name=="Baron"?0:1).ToList();}
 public static Size Size(Snapshot s){return new Size(Math.Max(1,Active(s).Count)*208-8,106);}
 static System.Drawing.Drawing2D.GraphicsPath Round(RectangleF r,float radius){var p=new System.Drawing.Drawing2D.GraphicsPath();float d=radius*2;p.AddArc(r.X,r.Y,d,d,180,90);p.AddArc(r.Right-d,r.Y,d,d,270,90);p.AddArc(r.Right-d,r.Bottom-d,d,d,0,90);p.AddArc(r.X,r.Bottom-d,d,d,90,90);p.CloseFigure();return p;}
 static void Face(Graphics g,int x,bool elder,Color accent){var state=g.Save();g.TranslateTransform(x+13,16);g.ScaleTransform(.70f,.70f);Color face=elder?Color.FromArgb(145,190,202):Color.FromArgb(139,63,205);using(var brush=new SolidBrush(face)){g.FillPolygon(brush,new[]{new Point(43,6),new Point(32,24),new Point(20,10),new Point(2,0),new Point(12,31),new Point(0,53),new Point(17,60),new Point(22,85),new Point(32,73),new Point(43,104),new Point(54,73),new Point(64,85),new Point(69,60),new Point(86,53),new Point(74,31),new Point(84,0),new Point(66,10),new Point(54,24)});g.FillPolygon(brush,new[]{new Point(17,34),new Point(10,16),new Point(16,-4),new Point(30,-15),new Point(24,6),new Point(31,24)});g.FillPolygon(brush,new[]{new Point(69,34),new Point(76,16),new Point(70,-4),new Point(56,-15),new Point(62,6),new Point(55,24)});}using(var dark=new SolidBrush(Color.FromArgb(18,20,27))){g.FillPolygon(dark,new[]{new Point(17,41),new Point(34,49),new Point(35,67),new Point(22,58)});g.FillPolygon(dark,new[]{new Point(69,41),new Point(52,49),new Point(51,67),new Point(64,58)});g.FillPolygon(dark,new[]{new Point(43,71),new Point(36,84),new Point(43,96),new Point(50,84)});}using(var eyes=new SolidBrush(accent)){g.FillPolygon(eyes,new[]{new Point(22,47),new Point(31,52),new Point(32,59),new Point(26,56)});g.FillPolygon(eyes,new[]{new Point(64,47),new Point(55,52),new Point(54,59),new Point(60,56)});}g.Restore(state);}
 public static void Draw(Graphics g,Snapshot snapshot){g.Clear(Theme.Background);g.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;g.TextRenderingHint=System.Drawing.Text.TextRenderingHint.AntiAliasGridFit;int x=0;foreach(var buff in Active(snapshot)){bool elder=buff.Name=="Elder";var accent=elder?Color.FromArgb(130,245,219):Color.FromArgb(195,105,245);using(var path=Round(new RectangleF(x+1,1,198,103),12))using(var fill=new SolidBrush(Color.FromArgb(17,19,25)))using(var edge=new Pen(Color.FromArgb(43,47,60),1.5f)){g.FillPath(fill,path);g.DrawPath(edge,path);}Face(g,x,elder,accent);using(var label=new Font("Segoe UI",10,FontStyle.Bold))using(var timer=new Font("Segoe UI",27,FontStyle.Bold))using(var ink=new SolidBrush(accent)){g.DrawString(elder?"ELDER":"BARON",label,Brushes.White,x+103,18);double seconds=Math.Ceiling(Math.Max(0,buff.Ends-snapshot.Time));g.DrawString(((int)seconds/60)+":"+((int)seconds%60).ToString("00"),timer,ink,x+91,35);using(var track=new Pen(Color.FromArgb(43,47,60),4)){track.StartCap=track.EndCap=System.Drawing.Drawing2D.LineCap.Round;g.DrawLine(track,x+98,87,x+181,87);}using(var progress=new Pen(accent,4)){progress.StartCap=progress.EndCap=System.Drawing.Drawing2D.LineCap.Round;g.DrawLine(progress,x+98,87,x+98+83*(float)((buff.Ends-snapshot.Time)/BuffWindow.Duration(buff.Name)),87);}}x+=208;}}
}
public sealed class ScoreboardAlignment:Form {
 public readonly OverlayOptions Result;readonly Panel preview=new Panel();readonly CompactOverlayVisuals visual;readonly Snapshot demo=CompactOverlayVisuals.Demo();
 public ScoreboardAlignment(DataStore data,OverlayOptions options){Result=options.Copy();visual=new CompactOverlayVisuals(data);Text="Align scoreboard overlay";ClientSize=new Size(1040,650);StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;Font=new Font("Segoe UI",10);
  Controls.Add(new Label{Text="Match your scoreboard position and scale.\nValues use a 1920 × 1080 reference; placement scales with the game window.\n\nRows: Top, Jungle, Mid, Bot, Support.\nKeep your scoreboard in this order. Role labels remain visible to identify each comparison.",Left=20,Top=20,Width=300,Height=160});
  Add("Horizontal offset",Result.BoardX,-1000,1000,198,v=>Result.BoardX=v);Add("Top position",Result.BoardY,0,900,247,v=>Result.BoardY=v);Add("Scale (%)",Result.BoardScale,60,160,296,v=>Result.BoardScale=v);Add("First row offset",Result.RowStart,90,300,345,v=>Result.RowStart=v);Add("Row spacing",Result.RowGap,50,140,394,v=>Result.RowGap=v);
  var flip=new CheckBox{Text="Allies on the left of scoreboard",Checked=Result.AlliesLeft,Left=20,Top=455,Width=300};flip.CheckedChanged+=(s,e)=>{Result.AlliesLeft=flip.Checked;preview.Invalidate();};Controls.Add(flip);
  var done=new Button{Text="Use this alignment",Left=20,Top=568,Width=290,Height=36,DialogResult=DialogResult.OK};Controls.Add(done);preview.SetBounds(340,20,680,600);preview.Paint+=(s,e)=>{e.Graphics.Clear(Theme.Background);var bounds=ScoreboardLayout.Bounds(new Rectangle(0,0,1080,1080),Result);using(var b=new Bitmap(bounds.Width,bounds.Height))using(var g=Graphics.FromImage(b)){visual.DrawBoard(g,demo.Overlay,Result,ScoreboardLayout.Scale(new Size(1080,1080),Result));b.MakeTransparent(Color.Magenta);e.Graphics.DrawImage(b,new Rectangle((int)(bounds.X*.55f),(int)(bounds.Y*.55f),(int)(bounds.Width*.55f),(int)(bounds.Height*.55f)));}};Controls.Add(preview);Theme.Apply(this);
 }
 void Add(string text,int value,int min,int max,int y,Action<int> change){Controls.Add(new Label{Text=text,Left=20,Top=y,Width=185,Height=28});var n=new NumericUpDown{Left=212,Top=y,Width=95,Minimum=min,Maximum=max,Value=Math.Max(min,Math.Min(max,value))};n.ValueChanged+=(s,e)=>{change((int)n.Value);preview.Invalidate();};Controls.Add(n);}
 protected override void Dispose(bool disposing){if(disposing)visual.Dispose();base.Dispose(disposing);}
}
}
