using System;
using System.Drawing;
using System.Windows.Forms;

namespace RiftReference {
public static class PanelSizing {
 public static Size Fit(Size natural,int width,int height,Size viewport){return new Size(Math.Min(Math.Max(1,viewport.Width),width>0?Math.Max(120,width):natural.Width/2),Math.Min(Math.Max(1,viewport.Height),height>0?Math.Max(40,height):natural.Height/2));}
 public static void Migrate(OverlayOptions opt){if(opt.PanelSizeVersion>=1)return;opt.BuildWidth/=2;opt.BuildHeight/=2;opt.BuffsWidth/=2;opt.BuffsHeight/=2;opt.StatsWidth/=2;opt.StatsHeight/=2;opt.PanelSizeVersion=1;}
 public static void Copy(OverlayOptions from,OverlayOptions to){to.PanelSizeVersion=from.PanelSizeVersion;to.BuildWidth=from.BuildWidth;to.BuildHeight=from.BuildHeight;to.BuffsWidth=from.BuffsWidth;to.BuffsHeight=from.BuffsHeight;to.StatsWidth=from.StatsWidth;to.StatsHeight=from.StatsHeight;to.BuildOpacity=from.BuildOpacity;to.BuffsOpacity=from.BuffsOpacity;to.StatsOpacity=from.StatsOpacity;}
 public static void Draw(Graphics g,Size target,Size natural,Action<Graphics> paint){g.Clear(Color.FromArgb(19,29,35));var saved=g.Save();float scale=Math.Min(target.Width/(float)natural.Width,target.Height/(float)natural.Height);try{g.TranslateTransform((target.Width-natural.Width*scale)/2,0);g.ScaleTransform(scale,scale);g.SetClip(new Rectangle(2,2,natural.Width-4,natural.Height-4));paint(g);}finally{g.Restore(saved);}using(var p=new Pen(Color.FromArgb(168,146,88)))g.DrawRectangle(p,1,1,target.Width-2,target.Height-2);}
}
public static class PanelTransparency {
 public static int Clamp(int value){return Math.Max(20,Math.Min(100,value));}
 public static bool Settings(IWin32Window owner,int current,Action<int> preview){int original=Clamp(current);using(var form=new Form{Text="Panel transparency",ClientSize=new Size(360,180),StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false}){var label=new Label{Left=18,Top=16,Width=325,Height=30};var slider=new TrackBar{Left=18,Top=48,Width=325,Minimum=20,Maximum=100,TickFrequency=10,Value=original};Action update=()=>{label.Text="Opacity: "+slider.Value+"% · lower is more transparent";preview(slider.Value);};slider.ValueChanged+=(s,e)=>update();var save=new Button{Text="Use opacity",Left=120,Top=126,Width=110,DialogResult=DialogResult.OK};var cancel=new Button{Text="Cancel",Left=240,Top=126,Width=100,DialogResult=DialogResult.Cancel};form.Controls.AddRange(new Control[]{label,slider,save,cancel});form.AcceptButton=save;form.CancelButton=cancel;Theme.Apply(form);update();if(form.ShowDialog(owner)==DialogResult.OK)return true;preview(original);return false;}}
 public static void Draw(Graphics g,Size size,Action<Graphics> painter,int opacity,Color background){using(var bitmap=new Bitmap(size.Width,size.Height)){using(var canvas=Graphics.FromImage(bitmap))painter(canvas);g.Clear(background);using(var attributes=new System.Drawing.Imaging.ImageAttributes()){var matrix=new System.Drawing.Imaging.ColorMatrix();matrix.Matrix33=Clamp(opacity)/100f;attributes.SetColorMatrix(matrix);g.DrawImage(bitmap,new Rectangle(Point.Empty,size),0,0,size.Width,size.Height,GraphicsUnit.Pixel,attributes);}}}
}
public static class PanelPositions {
 static double Unit(double n){return Double.IsNaN(n)||Double.IsInfinity(n)?0:Math.Max(0,Math.Min(1,n));}
 static Point Place(Rectangle game,Size panel,double u,double v){return new Point(game.Left+(int)Math.Round(Math.Max(0,game.Width-panel.Width)*Unit(u)),game.Top+(int)Math.Round(Math.Max(0,game.Height-panel.Height)*Unit(v)));}
 public static Point Build(Rectangle game,Size panel,OverlayOptions opt){
  if(opt.BuildPlaced)return Place(game,panel,opt.BuildU,opt.BuildV);
  if(opt.PanelLayoutVersion==0&&(opt.X!=24||opt.Y!=160))return Place(game,panel,opt.X/1490.0,opt.Y/878.0);
  int minimap=(int)Math.Round(280*game.Height/1080.0);return new Point(game.Left+Math.Max(0,game.Width-minimap-24-panel.Width),game.Top+Math.Max(0,game.Height-panel.Height-24));
 }
 public static Point Buffs(Rectangle game,Size panel,OverlayOptions opt){return opt.BuffsPlaced?Place(game,panel,opt.BuffsU,opt.BuffsV):new Point(game.Left+Math.Max(0,(game.Width-panel.Width)/2),game.Top+Math.Min(24,Math.Max(0,game.Height-panel.Height)));}
 public static void Store(Rectangle game,Rectangle panel,bool build,OverlayOptions opt){double u=(panel.Left-game.Left)/(double)Math.Max(1,game.Width-panel.Width),v=(panel.Top-game.Top)/(double)Math.Max(1,game.Height-panel.Height);opt.PanelLayoutVersion=1;if(build){opt.BuildPlaced=true;opt.BuildU=Unit(u);opt.BuildV=Unit(v);}else{opt.BuffsPlaced=true;opt.BuffsU=Unit(u);opt.BuffsV=Unit(v);}}
 public static void Migrate(OverlayOptions opt){if(opt.PanelLayoutVersion!=0)return;var game=new Rectangle(0,0,1920,1080);var size=new Size(430,202);if(opt.X!=24||opt.Y!=160)Store(game,new Rectangle(Build(game,size,opt),size),true,opt);opt.PanelLayoutVersion=1;}
}
public sealed class DraggableOverlayPanel:Control {
 public bool StaticDisplay;public int PanelOpacity=96;public string Caption;public Size NaturalSize=new Size(300,124);
 public void AddSetting(string name,Action action){menu.Items.Insert(0,new ToolStripMenuItem(name,null,(s,e)=>action()));}
 public event Action Closed,ResetRequested,LockChanged;
 readonly Button lockButton=new Button(),gearButton=new Button(),closeButton=new Button();readonly ToolTip tips=new ToolTip();readonly ContextMenuStrip menu=new ContextMenuStrip();
 public bool Locked=true;public Action<Graphics> Painter;public event Action Dropped;
 bool dragging;Point grab;Rectangle startBounds;int edges;
 public DraggableOverlayPanel(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);var buttons=new[]{lockButton,gearButton,closeButton};string[] names={"Lock position","Panel settings","Close panel"};for(int i=0;i<3;i++){var button=buttons[i];button.Name=names[i];button.AccessibleName=names[i];button.Size=new Size(12,12);button.FlatStyle=FlatStyle.Flat;button.BackColor=Color.FromArgb(19,29,35);button.ForeColor=Theme.Ink;button.FlatAppearance.BorderColor=Theme.Border;Controls.Add(button);tips.SetToolTip(button,names[i]);int glyph=i;button.Paint+=(s,e)=>DrawGlyph(e.Graphics,glyph);}Resize+=(s,e)=>{for(int i=0;i<3;i++)buttons[i].Location=new Point(Width-46+i*14,2);};lockButton.Click+=(s,e)=>SetLocked(!Locked);menu.Items.Add("Reset this panel's position",null,(s,e)=>{if(ResetRequested!=null)ResetRequested();});gearButton.Click+=(s,e)=>menu.Show(gearButton,new Point(0,gearButton.Height));closeButton.Click+=(s,e)=>{SetLocked(true);Hide();if(Closed!=null)Closed();};}
 void DrawGlyph(Graphics g,int glyph){g.ScaleTransform(0.48f,0.48f);using(var p=new Pen(Theme.Ink,1.5f)){if(glyph==0){g.DrawRectangle(p,7,11,11,9);g.DrawArc(p,Locked?9:5,4,7,11,180,180);}else if(glyph==1){g.DrawEllipse(p,8,8,9,9);for(int i=0;i<8;i++){double a=i*Math.PI/4;g.DrawLine(p,12.5f+(float)Math.Cos(a)*6,12.5f+(float)Math.Sin(a)*6,12.5f+(float)Math.Cos(a)*9,12.5f+(float)Math.Sin(a)*9);}}else{g.DrawLine(p,8,8,17,17);g.DrawLine(p,17,8,8,17);}}}
 protected override void OnPaint(PaintEventArgs e){if(StaticDisplay){if(Painter!=null)Painter(e.Graphics);return;}if(Painter!=null)PanelTransparency.Draw(e.Graphics,Size,Painter,PanelOpacity,Parent==null?Theme.Background:Parent.BackColor);using(var b=new SolidBrush(Color.FromArgb(19,29,35)))e.Graphics.FillRectangle(b,2,1,Width-4,Math.Max(14,(int)(Math.Min(Width/(float)NaturalSize.Width,Height/(float)NaturalSize.Height)*(Caption=="ITEM BUILD"?45:Caption=="YOUR STATS"?34:28))));using(var headerFont=new Font("Segoe UI",6.5f))TextRenderer.DrawText(e.Graphics,Caption??"PANEL",headerFont,new Rectangle(5,2,Width-52,13),Theme.Ink,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis);if(!Locked)using(var p=new Pen(Theme.Accent,3))e.Graphics.DrawRectangle(p,1,1,Width-3,Height-3);}
 int Edges(Point p){return (p.X<7?1:p.X>=Width-7?2:0)|(p.Y<7?4:p.Y>=Height-7?8:0);}
 void SetCursor(int hit){Cursor=StaticDisplay||Locked?Cursors.Default:hit==5||hit==10?Cursors.SizeNWSE:hit==6||hit==9?Cursors.SizeNESW:(hit&3)!=0?Cursors.SizeWE:(hit&12)!=0?Cursors.SizeNS:Cursors.SizeAll;}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);if(StaticDisplay||Locked||e.Button!=MouseButtons.Left)return;dragging=true;edges=Edges(e.Location);startBounds=Bounds;grab=new Point(Left+e.X,Top+e.Y);Capture=true;}
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);SetCursor(dragging?edges:Edges(e.Location));if(!dragging||Locked||Parent==null)return;int dx=Left+e.X-grab.X,dy=Top+e.Y-grab.Y;int maxW=Parent.ClientSize.Width,maxH=Parent.ClientSize.Height;if(edges==0){Location=new Point(Math.Max(0,Math.Min(startBounds.Left+dx,maxW-Width)),Math.Max(0,Math.Min(startBounds.Top+dy,maxH-Height)));return;}int l=startBounds.Left,t=startBounds.Top,r=startBounds.Right,b=startBounds.Bottom;int minW=Math.Min(120,maxW),minH=Math.Min(40,maxH);if((edges&1)!=0)l=Math.Max(0,Math.Min(l+dx,r-minW));if((edges&2)!=0)r=Math.Min(maxW,Math.Max(r+dx,l+minW));if((edges&4)!=0)t=Math.Max(0,Math.Min(t+dy,b-minH));if((edges&8)!=0)b=Math.Min(maxH,Math.Max(b+dy,t+minH));Bounds=Rectangle.FromLTRB(l,t,r,b);Invalidate();}
 protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);if(!dragging)return;dragging=false;Capture=false;if(Dropped!=null)Dropped();}
 protected override void OnMouseCaptureChanged(EventArgs e){base.OnMouseCaptureChanged(e);if(dragging&&!Capture){dragging=false;if(Dropped!=null)Dropped();}}
 public void SetLocked(bool value){if(StaticDisplay)value=true;Locked=value;dragging=false;Capture=false;Cursor=value?Cursors.Default:Cursors.SizeAll;tips.SetToolTip(lockButton,value?"Unlock this panel":"Lock this panel");lockButton.AccessibleName=value?"Unlock this panel":"Lock this panel";lockButton.Invalidate();Invalidate();if(LockChanged!=null)LockChanged();}
 protected override void Dispose(bool disposing){if(disposing){tips.Dispose();menu.Dispose();}base.Dispose(disposing);}
}
public sealed class PanelLayoutEditor:Form {
 public readonly OverlayOptions Result;readonly CompactOverlayVisuals visuals;readonly Snapshot demo=CompactOverlayVisuals.Demo();
 readonly DraggableOverlayPanel build=new DraggableOverlayPanel(),buffs=new DraggableOverlayPanel(),stats=new DraggableOverlayPanel{Caption="YOUR STATS"};
 public PanelLayoutEditor(DataStore data,OverlayOptions original){Result=original.Copy();PanelPositions.Migrate(Result);visuals=new CompactOverlayVisuals(data);Text="Rift Ready · Position overlay panels";FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.Manual;Bounds=Screen.PrimaryScreen.Bounds;BackColor=Theme.Background;AutoScaleMode=AutoScaleMode.None;KeyPreview=true;
  var demoOptions=Result.Copy();demoOptions.Champion="Vayne";demoOptions.Target=3153;build.Size=new Size(430,202);buffs.Size=new Size(300,124);build.Painter=g=>visuals.DrawBuild(g,demo.Overlay,demoOptions);buffs.Painter=g=>visuals.DrawBuffs(g,demo);Controls.Add(build);Controls.Add(buffs);
  build.NaturalSize=new Size(430,202);build.Caption="ITEM BUILD";buffs.Caption="BUFF TIMERS · EST.";
  build.Painter=g=>PanelSizing.Draw(g,build.Size,new Size(430,202),p=>visuals.DrawBuild(p,demo.Overlay,demoOptions));buffs.StaticDisplay=true;foreach(Control button in buffs.Controls)button.Visible=false;buffs.Painter=g=>visuals.DrawBuffs(g,demo);
  build.Dropped+=()=>{Result.BuildWidth=build.Width;Result.BuildHeight=build.Height;PanelPositions.Store(ClientRectangle,build.Bounds,true,Result);};buffs.Dropped+=()=>{Result.BuffsWidth=buffs.Width;Result.BuffsHeight=buffs.Height;PanelPositions.Store(ClientRectangle,buffs.Bounds,false,Result);};
  build.Closed+=()=>Result.Purchase=false;buffs.Closed+=()=>Result.Buffs=false;
  build.AddSetting("Transparency…",()=>PanelTransparency.Settings(this,Result.BuildOpacity,value=>{Result.BuildOpacity=build.PanelOpacity=value;build.Invalidate();}));buffs.AddSetting("Transparency…",()=>PanelTransparency.Settings(this,Result.BuffsOpacity,value=>{Result.BuffsOpacity=buffs.PanelOpacity=value;buffs.Invalidate();}));stats.AddSetting("Transparency…",()=>PanelTransparency.Settings(this,Result.StatsOpacity,value=>{Result.StatsOpacity=stats.PanelOpacity=value;stats.Invalidate();}));
  stats.Size=StatsPanel.Size(Result);stats.Painter=g=>StatsPanel.Draw(g,StatsPanel.Sample(),Result);Controls.Add(stats);stats.Dropped+=()=>StatsPanel.Store(ClientRectangle,stats.Bounds,Result);stats.Closed+=()=>Result.Stats=false;stats.ResetRequested+=()=>{Result.StatsPlaced=false;Arrange();};stats.AddSetting("Choose displayed stats…",()=>{if(StatsPanel.Settings(this,Result)){stats.Size=StatsPanel.Size(Result);stats.Visible=Result.Stats;Arrange();}});
  stats.Painter=g=>PanelSizing.Draw(g,stats.Size,StatsPanel.Size(Result),p=>StatsPanel.Draw(p,StatsPanel.Sample(),Result));stats.Dropped+=()=>{Result.StatsWidth=stats.Width;Result.StatsHeight=stats.Height;};
  stats.AddSetting("Reset size",()=>{Result.StatsWidth=Result.StatsHeight=0;Arrange();});build.AddSetting("Reset size",()=>{Result.BuildWidth=Result.BuildHeight=0;Arrange();});buffs.AddSetting("Reset size",()=>{Result.BuffsWidth=Result.BuffsHeight=0;Arrange();});
  build.ResetRequested+=()=>{Result.BuildPlaced=false;Arrange();};buffs.ResetRequested+=()=>{Result.BuffsPlaced=false;Arrange();};
  foreach(var panel in new[]{build,stats}){panel.AddSetting("Use layout · Ctrl+Enter",()=>Finish(true));panel.AddSetting("Cancel layout · Esc",()=>Finish(false));panel.AddSetting("Next preview screen · F6",NextScreen);}
  build.AddSetting("Reset this panel",()=>{Result.BuildPlaced=false;Result.BuildWidth=Result.BuildHeight=0;Result.BuildOpacity=96;Arrange();});stats.AddSetting("Reset this panel",()=>{Result.StatsPlaced=false;Result.StatsWidth=Result.StatsHeight=0;Result.StatsOpacity=96;Arrange();});
  Shown+=(s,e)=>{Arrange();build.Visible=Result.Purchase;buffs.Visible=Result.Buffs;stats.Visible=Result.Stats;};Resize+=(s,e)=>Arrange();
 }
 void Finish(bool save){DialogResult=save?DialogResult.OK:DialogResult.Cancel;Close();}
 void NextScreen(){var screens=Screen.AllScreens;int current=Array.FindIndex(screens,scr=>scr.Bounds==Bounds);Bounds=screens[(current+1)%screens.Length].Bounds;Arrange();}
 protected override bool ProcessCmdKey(ref Message msg,Keys keyData){if(keyData==(Keys.Control|Keys.Enter)){Finish(true);return true;}if(keyData==Keys.Escape){Finish(false);return true;}if(keyData==Keys.F6){NextScreen();return true;}return base.ProcessCmdKey(ref msg,keyData);}
 void Arrange(){build.PanelOpacity=PanelTransparency.Clamp(Result.BuildOpacity);buffs.PanelOpacity=PanelTransparency.Clamp(Result.BuffsOpacity);stats.PanelOpacity=PanelTransparency.Clamp(Result.StatsOpacity);build.Size=PanelSizing.Fit(new Size(430,202),Result.BuildWidth,Result.BuildHeight,ClientSize);buffs.Size=BuffCards.Size(demo);stats.NaturalSize=StatsPanel.Size(Result);stats.Size=PanelSizing.Fit(stats.NaturalSize,Result.StatsWidth,Result.StatsHeight,ClientSize);build.Location=PanelPositions.Build(ClientRectangle,build.Size,Result);buffs.Location=new Point(Math.Max(0,(ClientSize.Width-buffs.Width)/2),24);stats.Location=StatsPanel.Position(ClientRectangle,stats.Size,Result);Invalidate();}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);int map=(int)(280*ClientSize.Height/1080.0);var box=new Rectangle(ClientSize.Width-map,ClientSize.Height-map,map,map);using(var brush=new SolidBrush(Color.FromArgb(25,34,38)))e.Graphics.FillRectangle(brush,box);TextRenderer.DrawText(e.Graphics,"MINIMAP AREA\n(default size reference)",Font,box,Theme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.WordBreak);}
 protected override void Dispose(bool disposing){if(disposing)visuals.Dispose();base.Dispose(disposing);}
}
}
