using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using RiftReference.Release;

namespace RiftReference {
public sealed class SettingsCard : Panel {
 readonly Color marker;
 public SettingsCard(string name,int top,int height,Color accent){Name=name;Left=0;Top=top;Width=760;Height=height;Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;BackColor=Theme.Panel;marker=accent;SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.ResizeRedraw,true);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=SmoothingMode.AntiAlias;using(var pen=new Pen(Theme.Border))using(var path=Round(new Rectangle(0,0,Width-1,Height-1),12)){g.DrawPath(pen,path);}using(var brush=new SolidBrush(marker))g.FillRectangle(brush,0,18,3,34);}
 static GraphicsPath Round(Rectangle box,int radius){var path=new GraphicsPath();int d=radius*2;path.AddArc(box.Left,box.Top,d,d,180,90);path.AddArc(box.Right-d,box.Top,d,d,270,90);path.AddArc(box.Right-d,box.Bottom-d,d,d,0,90);path.AddArc(box.Left,box.Bottom-d,d,d,90,90);path.CloseFigure();return path;}
}

public sealed class OverlayPreferencesPage : Panel {
 readonly DataStore data;readonly OverlayOptions draft;readonly ComboBox champions=new ComboBox(),items=new ComboBox(),keys=new ComboBox();readonly Label status=new Label();readonly TextBox search=new TextBox();
 readonly CheckBox enabled=new CheckBox(),gameBar=new CheckBox(),gold=new CheckBox(),buffs=new CheckBox(),purchase=new CheckBox(),stats=new CheckBox(),cspm=new CheckBox(),kp=new CheckBox(),cs=new CheckBox(),kda=new CheckBox(),vision=new CheckBox();HashSet<int> planIds;
 public OverlayPreferencesPage(DataStore data,OverlayOptions current){this.data=data;draft=current.Copy();Name="OverlayPage";Dock=DockStyle.Fill;AutoScroll=true;BackColor=Theme.Background;Build();}
 void Build(){
  var fullscreen=Card("OverlayDisplayCard",0,144,"FULLSCREEN DISPLAY","Choose how Rift Ready appears over League.");
  Check(fullscreen,enabled,"Enable the game overlay",draft.Enabled,24,66,330);Check(fullscreen,gameBar,"Use Game Bar in fullscreen",draft.GameBar,376,66,275);
  var open=new Button{Text="Open Game Bar",Left=536,Top=99,Width=190,Height=32};open.Click+=(s,e)=>{try{GameBarIntegration.Open();status.Text=GameBarIntegration.SetupStatus;}catch{status.Text="Could not open Game Bar. Open it from the Windows Game Bar widget menu.";}};fullscreen.Controls.Add(open);
  var connection=new Label{Text=GameBarIntegration.SetupStatus,Left=24,Top=100,Width=495,Height=34,ForeColor=Theme.Muted};fullscreen.Controls.Add(connection);

  var visible=Card("OverlayVisibleCard",160,210,"VISIBLE INFORMATION","Select the information that can appear during a match.");
  Check(visible,gold,"Lane item-value difference while the scoreboard key is held",draft.Gold,24,64,330);Check(visible,buffs,"Baron and Elder buff windows",draft.Buffs,24,96,325);Check(visible,purchase,"Item and component purchase progress",draft.Purchase,376,96,350);Check(visible,stats,"Personal stats panel",draft.Stats,24,128,300);
  Label(visible,"Scoreboard key",376,64,130,24);keys.SetBounds(506,60,220,28);keys.Name="ScoreboardKey";keys.DropDownStyle=ComboBoxStyle.DropDownList;foreach(Keys key in new[]{Keys.Tab,Keys.Space,Keys.Oemtilde,Keys.F1,Keys.F2,Keys.F3,Keys.F4})keys.Items.Add(key);keys.SelectedItem=(Keys)draft.Key;if(keys.SelectedIndex<0)keys.SelectedIndex=0;visible.Controls.Add(keys);
  Label(visible,"Stats shown",24,166,120,24);Check(visible,cspm,"CS/min",draft.StatsCspm,142,164,88);Check(visible,kp,"Kill participation",draft.StatsKp,234,164,145);Check(visible,cs,"CS",draft.StatsCs,386,164,58);Check(visible,kda,"K/D/A",draft.StatsKda,450,164,76);Check(visible,vision,"Vision",draft.StatsVision,534,164,92);

  var layout=Card("OverlayLayoutCard",386,130,"LAYOUT + ALIGNMENT","Tune the panels once, then keep them locked and click-through in game.");
  var move=new Button{Text="Move / resize panels",Left=24,Top=74,Width=220,Height=34};move.Click+=(s,e)=>EditLayout();layout.Controls.Add(move);
  var align=new Button{Text="Align scoreboard",Left=258,Top=74,Width=210,Height=34};align.Click+=(s,e)=>AlignScoreboard();layout.Controls.Add(align);
  var resetStats=new Button{Text="Reset stats",Left=482,Top=74,Width=220,Height=34};resetStats.Click+=(s,e)=>{stats.Checked=true;cspm.Checked=true;kp.Checked=true;cs.Checked=false;kda.Checked=false;vision.Checked=false;status.Text="Stats reset to the compact CS/min and kill-participation view.";};layout.Controls.Add(resetStats);

  var target=Card("OverlayTargetCard",532,190,"PURCHASE TARGET","Choose a champion and item, or load a saved Rift Ready build.");
  champions.SetBounds(24,68,235,29);champions.Name="OverlayChampion";champions.DropDownStyle=ComboBoxStyle.DropDownList;foreach(var c in data.Champions.OrderBy(c=>data.Name(c.Key)))champions.Items.Add(new BuildChoice((int)J.N(c.Value,"key"),data.Name(c.Key)));target.Controls.Add(champions);champions.SelectedItem=champions.Items.Cast<BuildChoice>().FirstOrDefault(c=>data.Resolve(c.Id.ToString())==draft.Champion);
  var choose=new Button{Text="Choose build",Left=272,Top=66,Width=135,Height=32};choose.Click+=(s,e)=>ChooseBuild();target.Controls.Add(choose);
  var load=new Button{Text="Load saved plan",Left=419,Top=66,Width=145,Height=32};load.Click+=(s,e)=>LoadPlan();target.Controls.Add(load);
  var all=new Button{Text="All items",Left=576,Top=66,Width=126,Height=32};all.Click+=(s,e)=>{planIds=null;draft.Source="Manual selection";Populate();};target.Controls.Add(all);
  Label(target,"Find item",24,110,90,24);search.SetBounds(116,106,268,28);search.Name="OverlayItemSearch";search.TextChanged+=(s,e)=>Populate();target.Controls.Add(search);items.SetBounds(398,106,304,30);items.Name="OverlayItem";items.DropDownStyle=ComboBoxStyle.DropDownList;target.Controls.Add(items);Populate();items.SelectedItem=items.Items.Cast<BuildChoice>().FirstOrDefault(c=>c.Id==draft.Target);
  status.SetBounds(24,145,678,36);status.Name="OverlayStatus";status.ForeColor=Theme.Muted;status.Text="Inventory-value and buff-window estimates use visible match data. The League shop remains authoritative.";target.Controls.Add(status);
  Theme.Apply(this);StylePrimary(open);
 }
 SettingsCard Card(string name,int top,int height,string heading,string detail){var card=new SettingsCard(name,top,height,Theme.Accent);var title=new Label{Text=heading,Left=24,Top=17,Width=680,Height=24,Font=new Font("Segoe UI",11,FontStyle.Bold),ForeColor=Theme.Ink};var note=new Label{Text=detail,Left=24,Top=40,Width=690,Height=22,ForeColor=Theme.Muted};card.Controls.AddRange(new Control[]{title,note});Controls.Add(card);return card;}
 static void Label(Control parent,string text,int x,int y,int w,int h){parent.Controls.Add(new Label{Text=text,Left=x,Top=y,Width=w,Height=h,ForeColor=Theme.Ink});}
 static void Check(Control parent,CheckBox box,string text,bool value,int x,int y,int width){box.Text=text;box.Checked=value;box.SetBounds(x,y,width,26);box.ForeColor=Theme.Ink;parent.Controls.Add(box);}
 static void StylePrimary(Button button){button.BackColor=Theme.Accent;button.ForeColor=Theme.Background;button.FlatAppearance.BorderColor=Theme.Accent;}
 void EditLayout(){var current=Commit();using(var editor=new PanelLayoutEditor(data,current))if(editor.ShowDialog(FindForm())==DialogResult.OK){StatsPanel.Copy(editor.Result,draft);PanelSizing.Copy(editor.Result,draft);draft.PanelLayoutVersion=1;draft.BuildPlaced=editor.Result.BuildPlaced;draft.BuffsPlaced=editor.Result.BuffsPlaced;draft.BuildU=editor.Result.BuildU;draft.BuildV=editor.Result.BuildV;draft.BuffsU=editor.Result.BuffsU;draft.BuffsV=editor.Result.BuffsV;purchase.Checked=editor.Result.Purchase;buffs.Checked=editor.Result.Buffs;status.Text="Panel positions and sizes updated. Save preferences to keep them.";}}
 void AlignScoreboard(){using(var form=new ScoreboardAlignment(data,Commit()))if(form.ShowDialog(FindForm())==DialogResult.OK){draft.BoardX=form.Result.BoardX;draft.BoardY=form.Result.BoardY;draft.BoardScale=form.Result.BoardScale;draft.RowStart=form.Result.RowStart;draft.RowGap=form.Result.RowGap;draft.AlliesLeft=form.Result.AlliesLeft;status.Text="Scoreboard alignment updated. Save preferences to keep it.";}}
 void ChooseBuild(){try{var selected=champions.SelectedItem as BuildChoice;if(selected==null)throw new ArgumentException("Select your champion first.");using(var picker=new RecommendationPicker(data,data.Resolve(selected.Id.ToString())))if(picker.ShowDialog(FindForm())==DialogResult.OK)UsePlan(picker.PlanJson);}catch(Exception ex){status.Text=ex.Message;}}
 void UsePlan(string json){string champion,patch;var ids=OverlaySettings.PlanItems(data,json,out champion,out patch);if(Recommendations.Patch(patch)!=Recommendations.Patch(data.Version))throw new ArgumentException("Refresh the build for your current patch.");planIds=new HashSet<int>(ids);draft.PlanPatch=patch;draft.Source="Diamond+ selected build";champions.SelectedItem=champions.Items.Cast<BuildChoice>().First(c=>data.Resolve(c.Id.ToString())==champion);search.Clear();Populate();items.SelectedItem=items.Items.Cast<BuildChoice>().FirstOrDefault(c=>c.Id==ids[0]);status.Text="Selected build loaded. Choose the target item you want to track, then save preferences.";}
 void LoadPlan(){try{using(var dialog=new OpenFileDialog{Filter="Rift loadout (*.json)|*.json"})if(dialog.ShowDialog(FindForm())==DialogResult.OK){if(new FileInfo(dialog.FileName).Length>65536)throw new ArgumentException("Plan is too large.");UsePlan(File.ReadAllText(dialog.FileName,System.Text.Encoding.UTF8));draft.Source="Saved loadout plan";}}catch(Exception ex){status.Text=ex.Message;}}
 void Populate(){var chosen=items.SelectedItem as BuildChoice;items.Items.Clear();foreach(var pair in data.Items.Where(p=>OverlayData.Purchasable(data,Int32.Parse(p.Key))&&(planIds==null||planIds.Contains(Int32.Parse(p.Key)))&&J.S(p.Value,"name").IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0).OrderBy(p=>J.S(p.Value,"name")))items.Items.Add(new BuildChoice(Int32.Parse(pair.Key),J.S(pair.Value,"name")));if(chosen!=null)items.SelectedItem=items.Items.Cast<BuildChoice>().FirstOrDefault(c=>c.Id==chosen.Id);}
 public OverlayOptions Commit(){draft.Enabled=enabled.Checked;draft.GameBar=gameBar.Checked;draft.Gold=gold.Checked;draft.Buffs=buffs.Checked;draft.Purchase=purchase.Checked;draft.Stats=stats.Checked;draft.StatsCspm=cspm.Checked;draft.StatsKp=kp.Checked;draft.StatsCs=cs.Checked;draft.StatsKda=kda.Checked;draft.StatsVision=vision.Checked;draft.Key=(int)(Keys)keys.SelectedItem;var champion=champions.SelectedItem as BuildChoice;var item=items.SelectedItem as BuildChoice;draft.Champion=champion==null?"":data.Resolve(champion.Id.ToString());draft.Target=item==null?0:item.Id;return draft.Copy();}
}

public sealed class PreferencesDialog : MinimalWindow {
 readonly Preferences current;readonly AttentionAudio audio;readonly Func<Snapshot> snapshot;readonly Panel pageHost=new Panel();readonly Label pageTitle=new Label(),pageDetail=new Label();readonly List<NavigationButton> nav=new List<NavigationButton>();readonly List<Control> pages=new List<Control>();readonly Timer audioStatusTimer=new Timer{Interval=400};
 CheckBox adjust,monitor,enemiesLeft,coaching,master,tones,secondClick,tenCue,thirtyCue,minuteCue,voice,respawn,laneOnly;NumericUpDown poll,first,every,end;ComboBox focus,format;TrackBar volume;Label volumeLabel,audioStatus;OverlayPreferencesPage overlayPage;
 public Preferences Result;public OverlayOptions OverlayResult;
 public PreferencesDialog(DataStore data,Preferences preferences,OverlayOptions overlay,MobileCompanion mobile,Action publish,AttentionAudio audio,Func<Snapshot> snapshot,int selectedSection){current=preferences;this.audio=audio;this.snapshot=snapshot;Text="Rift Ready · Preferences";ClientSize=new Size(1040,900);MinimumSize=new Size(980,800);StartPosition=FormStartPosition.CenterParent;BackColor=Theme.Background;ForeColor=Theme.Ink;Font=new Font("Segoe UI",10);AutoScaleMode=AutoScaleMode.None;UseFixedDialogChrome();
  var rail=new Panel{Name="PreferencesNavigation",Left=0,Top=TitleHeight,Width=216,Height=ContentHeight,Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left,BackColor=Color.FromArgb(12,13,17)};Controls.Add(rail);
  rail.Controls.Add(new Label{Text="PREFERENCES",Left=20,Top=22,Width=175,Height=28,Font=new Font("Segoe UI",13,FontStyle.Bold),ForeColor=Theme.Ink});rail.Controls.Add(new Label{Text="RIFT READY",Left=20,Top=52,Width=175,Height=22,Font=new Font("Segoe UI",8,FontStyle.Bold),ForeColor=Theme.Accent});
  string[] names={"General","Game overlay","Audio & reminders","Phone / tablet"};string[] symbols={"general","overlay","audio","phone"};for(int i=0;i<names.Length;i++){int index=i;var button=new NavigationButton{Text=names[i],Symbol=symbols[i],Left=16,Top=104+i*52,Width=184,Height=44,BackColor=rail.BackColor,ForeColor=Theme.Ink,Font=new Font("Segoe UI",10)};button.Click+=(s,e)=>SelectSection(index);rail.Controls.Add(button);nav.Add(button);}
  rail.Controls.Add(new Label{Text="Settings are saved locally on this PC.",Left=20,Top=ContentHeight-70,Width=175,Height=45,Anchor=AnchorStyles.Left|AnchorStyles.Bottom,ForeColor=Theme.Muted});
  pageTitle.SetBounds(250,TitleHeight+22,500,30);pageTitle.Font=new Font("Segoe UI",18,FontStyle.Bold);pageTitle.ForeColor=Theme.Ink;pageTitle.UseMnemonic=false;Controls.Add(pageTitle);pageDetail.SetBounds(250,TitleHeight+53,540,28);pageDetail.ForeColor=Theme.Muted;Controls.Add(pageDetail);
  var save=new Button{Name="SavePreferences",Text="Save preferences",Width=166,Height=38,Anchor=AnchorStyles.Top|AnchorStyles.Right};save.Location=new Point(ClientSize.Width-190,TitleHeight+24);save.Click+=(s,e)=>SaveAndClose();Controls.Add(save);
  var cancel=new Button{Name="CancelPreferences",Text="Cancel",Width=104,Height=38,Anchor=AnchorStyles.Top|AnchorStyles.Right};cancel.Location=new Point(ClientSize.Width-306,TitleHeight+24);cancel.Click+=(s,e)=>{DialogResult=DialogResult.Cancel;Close();};Controls.Add(cancel);
  pageHost.Name="PreferencesPageHost";pageHost.SetBounds(240,TitleHeight+92,ClientSize.Width-264,ContentHeight-116);pageHost.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;pageHost.BackColor=Theme.Background;Controls.Add(pageHost);
  pages.Add(BuildGeneral());overlayPage=new OverlayPreferencesPage(data,overlay);pages.Add(overlayPage);pages.Add(BuildAudio());var phone=MobileSettings.CreatePanel(mobile,publish);phone.Name="PhonePage";phone.Dock=DockStyle.Fill;pages.Add(phone);foreach(var page in pages){page.Visible=false;pageHost.Controls.Add(page);}SelectSection(Math.Max(0,Math.Min(3,selectedSection)));
  audioStatusTimer.Tick+=(s,e)=>{if(audio.Status!=""&&audioStatus!=null)audioStatus.Text=audio.Status;};audioStatusTimer.Start();Theme.Apply(this);StylePrimary(save);Resize+=(s,e)=>LayoutCards();LayoutCards();
 }
 Panel BuildGeneral(){var page=Page("GeneralPage");var display=Card(page,"GeneralDisplayCard",0,190,"DISPLAY + DASHBOARD","Choose where Rift Ready opens and how often it refreshes.");adjust=Check(display,"Apply supported haste adjustments",current.Adjust,24,70,360);monitor=Check(display,"Open on the second monitor",current.SecondMonitor,24,108,360);Label(display,"Refresh interval",414,69,150,24);poll=new NumericUpDown{Name="PollSeconds",Minimum=3,Maximum=30,Value=Math.Max(3,Math.Min(30,current.PollSeconds)),Left=566,Top=66,Width=120};display.Controls.Add(poll);Label(display,"seconds",694,69,60,24);
  var coachingCard=Card(page,"GeneralCoachingCard",206,326,"COACHING + MATCH VIEW","Keep the information useful without changing the underlying match data.");Label(coachingCard,"One training focus",24,70,220,24);focus=new ComboBox{Name="TrainingFocus",Left=24,Top=96,Width=336,DropDownStyle=ComboBoxStyle.DropDownList};focus.Items.AddRange(Coaching.FocusNames.Cast<object>().ToArray());focus.SelectedItem=current.TrainingFocus;if(focus.SelectedIndex<0)focus.SelectedIndex=0;coachingCard.Controls.Add(focus);Label(coachingCard,"Cooldown display",390,70,220,24);format=new ComboBox{Name="CooldownFormat",Left=390,Top=96,Width=336,DropDownStyle=ComboBoxStyle.DropDownList};format.Items.AddRange(new object[]{"Minutes + seconds at 1 minute or more","Seconds only"});format.SelectedIndex=current.MinutesAndSeconds?0:1;coachingCard.Controls.Add(format);enemiesLeft=Check(coachingCard,"Enemies on the left side",current.EnemiesLeft,24,151,300);coaching=Check(coachingCard,"Show lane plan, enemy tools and training focus",current.ShowCoaching,390,151,345);Label(coachingCard,"You can also drag the allied and enemy lane headers to swap sides. Detailed matchup, teamfight and wave lessons remain in Playbook. Review notes stay local to this PC.",24,205,702,80);return page;}
 Panel BuildAudio(){var page=Page("AudioPage");var sound=Card(page,"AudioSoundCard",0,306,"AUDIO + REMINDERS","Choose the signals Rift Ready may play during live games.");master=Check(sound,"Enable audio during live games",current.AudioEnabled,24,70,330);tones=Check(sound,"Enable timing sounds",current.ToneCues,388,70,260);secondClick=Check(sound,"1s click",current.SecondClick,24,109,90);tenCue=Check(sound,"10 seconds",current.TenSecondCue,126,109,112);thirtyCue=Check(sound,"30 seconds",current.ThirtySecondCue,250,109,120);minuteCue=Check(sound,"1 minute",current.MinuteCue,382,109,100);voice=Check(sound,"Spoken jungle-awareness reminders",current.VoiceCues,24,148,325);respawn=Check(sound,"Announce enemy respawns",current.RespawnCues,388,148,260);laneOnly=Check(sound,"Only announce my lane opponents",current.RespawnLaneOnly,24,187,325);volumeLabel=Label(sound,"Volume: "+current.AudioVolume+"%",388,187,220,24);volume=new TrackBar{Name="AudioVolume",Minimum=0,Maximum=100,TickFrequency=10,Value=Math.Max(0,Math.Min(100,current.AudioVolume)),Left=388,Top=211,Width=320};volume.ValueChanged+=(s,e)=>volumeLabel.Text="Volume: "+volume.Value+"%";sound.Controls.Add(volume);
  var schedule=Card(page,"AudioScheduleCard",322,264,"JUNGLE AWARENESS SCHEDULE","These prompts are a schedule, not detection or a prediction of a gank.");Label(schedule,"First check",24,70,120,24);first=Number(schedule,current.JungleFirst,30,1800,30,24,96);Label(schedule,"Repeat every",190,70,130,24);every=Number(schedule,current.JungleInterval,30,600,30,190,96);Label(schedule,"Stop after",356,70,120,24);end=Number(schedule,current.JungleEnd,30,3600,30,356,96);Label(schedule,"seconds",500,101,75,24);var hear10=Preview(schedule,"Hear 10s",24,148,()=>audio.Tone(AttentionCue.TenSeconds,volume.Value,true));var hear30=Preview(schedule,"Hear 30s",148,148,()=>audio.Tone(AttentionCue.ThirtySeconds,volume.Value,true));var hearMinute=Preview(schedule,"Hear minute",272,148,()=>audio.Tone(AttentionCue.Minute,volume.Value,true));var hearVoice=Preview(schedule,"Hear voice",396,148,()=>audio.Speak(AttentionAudio.JungleMessage(snapshot()),volume.Value));var hearRespawn=Preview(schedule,"Hear respawn",520,148,()=>audio.Speak("Caitlyn is back alive.",volume.Value));audioStatus=Label(schedule,"Uses your Windows output device and installed English speech voice.",24,202,680,38);audioStatus.ForeColor=Theme.Muted;return page;}
 Panel Page(string name){return new Panel{Name=name,Dock=DockStyle.Fill,AutoScroll=true,BackColor=Theme.Background};}
 SettingsCard Card(Panel page,string name,int top,int height,string heading,string detail){var card=new SettingsCard(name,top,height,Theme.Accent);card.Controls.Add(new Label{Text=heading,Left=24,Top=17,Width=680,Height=24,Font=new Font("Segoe UI",11,FontStyle.Bold),ForeColor=Theme.Ink});card.Controls.Add(new Label{Text=detail,Left=24,Top=40,Width=690,Height=24,ForeColor=Theme.Muted});page.Controls.Add(card);return card;}
 static CheckBox Check(Control parent,string text,bool value,int x,int y,int width){var box=new CheckBox{Text=text,Checked=value,Left=x,Top=y,Width=width,Height=27,ForeColor=Theme.Ink};parent.Controls.Add(box);return box;}
 static Label Label(Control parent,string text,int x,int y,int width,int height){var label=new Label{Text=text,Left=x,Top=y,Width=width,Height=height,ForeColor=Theme.Ink};parent.Controls.Add(label);return label;}
 static NumericUpDown Number(Control parent,int value,int min,int max,int increment,int x,int y){var number=new NumericUpDown{Minimum=min,Maximum=max,Increment=increment,Value=Math.Max(min,Math.Min(max,value)),Left=x,Top=y,Width=132};parent.Controls.Add(number);return number;}
 static Button Preview(Control parent,string text,int x,int y,Action action){var button=new Button{Text=text,Left=x,Top=y,Width=112,Height=34};button.Click+=(s,e)=>action();parent.Controls.Add(button);return button;}
 static void StylePrimary(Button button){button.BackColor=Theme.Accent;button.ForeColor=Theme.Background;button.FlatAppearance.BorderColor=Theme.Accent;}
 void LayoutCards(){int width=Math.Max(720,pageHost.ClientSize.Width-18);foreach(var page in pages)foreach(var card in page.Controls.OfType<SettingsCard>())card.Width=width;}
 public void SelectSection(int index){string[] titles={"General","Game overlay","Audio & reminders","Phone / tablet"};string[] details={"Dashboard behavior and coaching preferences.","Fullscreen display, match panels and scoreboard alignment.","Timing cues, voice reminders and audio previews.","Use a trusted local network as a second screen."};for(int i=0;i<pages.Count;i++){pages[i].Visible=i==index;nav[i].Active=i==index;nav[i].Invalidate();}pageTitle.Text=titles[index];pageDetail.Text=details[index];}
 void SaveAndClose(){if(end.Value<first.Value){MessageBox.Show(this,"The last jungle check must be at or after the first check.");return;}Result=new Preferences{SettingsVersion=2,TrainingFocus=Convert.ToString(focus.SelectedItem),ShowCoaching=coaching.Checked,EnemiesLeft=enemiesLeft.Checked,AutoUpdates=current.AutoUpdates,Adjust=adjust.Checked,SecondMonitor=monitor.Checked,PollSeconds=(int)poll.Value,Focus=current.Focus,AudioEnabled=master.Checked,ToneCues=tones.Checked,SecondClick=secondClick.Checked,TenSecondCue=tenCue.Checked,ThirtySecondCue=thirtyCue.Checked,MinuteCue=minuteCue.Checked,VoiceCues=voice.Checked,RespawnCues=respawn.Checked,RespawnLaneOnly=laneOnly.Checked,MinutesAndSeconds=format.SelectedIndex==0,AudioVolume=volume.Value,JungleFirst=(int)first.Value,JungleInterval=(int)every.Value,JungleEnd=(int)end.Value};OverlayResult=overlayPage.Commit();DialogResult=DialogResult.OK;}
 public void CapturePages(string folder){StartPosition=FormStartPosition.Manual;Location=new Point(-30000,-30000);Show();Application.DoEvents();string[] names={"display-settings.png","overlay-preferences.png","audio-settings.png","mobile-settings.png"};for(int i=0;i<pages.Count;i++){SelectSection(i);Application.DoEvents();using(var image=new Bitmap(Width,Height)){DrawToBitmap(image,new Rectangle(Point.Empty,Size));image.Save(Path.Combine(folder,names[i]));}}Hide();}
 protected override void Dispose(bool disposing){if(disposing)audioStatusTimer.Dispose();base.Dispose(disposing);}
}

public sealed class UpdatesDialog : MinimalWindow {
 readonly UpdateManager updater;readonly Func<Task> checkUpdates;readonly Func<bool> canUpdate;readonly Action<bool> setAutomatic;readonly Label status=new Label();readonly TextBox notes=new TextBox();readonly Button check=new Button(),install=new Button();readonly SettingsCard releaseCard;readonly Label footer;
 public bool InstallLaunched;
 public UpdatesDialog(UpdateManager updater,bool automatic,Func<Task> checkUpdates,Func<bool> canUpdate,Action<bool> setAutomatic){this.updater=updater;this.checkUpdates=checkUpdates;this.canUpdate=canUpdate;this.setAutomatic=setAutomatic;Text="Rift Ready · Updates";ClientSize=new Size(820,560);MinimumSize=new Size(740,540);StartPosition=FormStartPosition.CenterParent;BackColor=Theme.Background;ForeColor=Theme.Ink;Font=new Font("Segoe UI",10);AutoScaleMode=AutoScaleMode.None;
  Controls.Add(new Label{Text="Updates",Left=36,Top=TitleHeight+26,Width=500,Height=34,Font=new Font("Segoe UI",20,FontStyle.Bold),ForeColor=Theme.Ink});Controls.Add(new Label{Text="Version checks and verified Rift Ready releases.",Left=38,Top=TitleHeight+62,Width=620,Height=26,ForeColor=Theme.Muted});
  var current=Card("CurrentVersionCard",36,TitleHeight+104,ClientSize.Width-72,122,"CURRENT VERSION","Rift Ready "+ReleaseInfo.Version);var automaticBox=new CheckBox{Text="Automatically check outside matches",Checked=automatic,Left=24,Top=77,Width=360,Height=28};automaticBox.CheckedChanged+=(s,e)=>setAutomatic(automaticBox.Checked);current.Controls.Add(automaticBox);
  releaseCard=Card("ReleaseCard",36,TitleHeight+242,ClientSize.Width-72,190,"RELEASE STATUS","Check for a new verified Rift Ready release.");status.SetBounds(24,76,releaseCard.Width-48,54);status.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;status.ForeColor=Theme.Muted;status.Text=updater.Status;releaseCard.Controls.Add(status);notes.SetBounds(24,130,releaseCard.Width-48,126);notes.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;notes.Multiline=true;notes.ReadOnly=true;notes.ScrollBars=ScrollBars.Vertical;notes.Text=updater.Available==null?"":updater.Available.notes;releaseCard.Controls.Add(notes);
  check.Text="Check for updates";check.SetBounds(36,TitleHeight+468,180,38);check.Anchor=AnchorStyles.Left|AnchorStyles.Bottom;check.Click+=async(s,e)=>await Check();Controls.Add(check);install.Text="Download and install";install.SetBounds(230,TitleHeight+468,210,38);install.Anchor=AnchorStyles.Left|AnchorStyles.Bottom;install.Enabled=updater.Available!=null;install.Click+=async(s,e)=>await Install();Controls.Add(install);footer=new Label{Text="Downloads use HTTPS and are checked against the Rift Ready publisher signature. Your saved preferences are retained.",Left=458,Top=TitleHeight+468,Width=310,Height=54,Anchor=AnchorStyles.Right|AnchorStyles.Bottom,ForeColor=Theme.Muted};Controls.Add(footer);Theme.Apply(this);RefreshReleaseLayout();
 }
 SettingsCard Card(string name,int x,int y,int width,int height,string heading,string detail){var card=new SettingsCard(name,y,height,Theme.Accent){Left=x,Width=width,Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};card.Controls.Add(new Label{Text=heading,Left=24,Top=17,Width=620,Height=24,Font=new Font("Segoe UI",11,FontStyle.Bold),ForeColor=Theme.Ink});card.Controls.Add(new Label{Text=detail,Left=24,Top=42,Width=620,Height=24,ForeColor=Theme.Ink});Controls.Add(card);return card;}
 async Task Check(){check.Enabled=false;status.Text="Checking for updates…";try{await checkUpdates();if(IsDisposed)return;status.Text=updater.Status;notes.Text=updater.Available==null?"":updater.Available.notes;install.Enabled=updater.Available!=null;RefreshReleaseLayout();}finally{if(!IsDisposed)check.Enabled=true;}}
 async Task Install(){if(!canUpdate()){status.Text="Finish champion select or your match before updating.";return;}install.Enabled=false;check.Enabled=false;try{status.Text="Downloading and verifying the release…";string file=await updater.Prepare();if(IsDisposed)return;if(!canUpdate()){status.Text="A match started. Install after it finishes.";return;}updater.Launch(file);InstallLaunched=true;DialogResult=DialogResult.OK;}catch(Exception ex){if(!IsDisposed)status.Text=ex.Message;}finally{if(!IsDisposed){check.Enabled=true;install.Enabled=updater.Available!=null;}}}
 public void CaptureImage(string path){StartPosition=FormStartPosition.Manual;Location=new Point(-30000,-30000);Show();Application.DoEvents();using(var image=new Bitmap(Width,Height)){DrawToBitmap(image,new Rectangle(Point.Empty,Size));image.Save(path);}Hide();}
 void RefreshReleaseLayout(){bool expanded=updater.Available!=null&&!String.IsNullOrWhiteSpace(notes.Text);ClientSize=new Size(ClientSize.Width,expanded?650:560);releaseCard.Height=expanded?286:190;notes.Visible=expanded;int top=TitleHeight+(expanded?548:468);check.Top=top;install.Top=top;footer.Top=top;if(install.Enabled)StylePrimary(install);else{install.BackColor=Theme.Panel;install.ForeColor=Theme.Muted;install.FlatAppearance.BorderColor=Theme.Border;}}
 static void StylePrimary(Button button){button.BackColor=Theme.Accent;button.ForeColor=Theme.Background;button.FlatAppearance.BorderColor=Theme.Accent;}
}
}
